"""Editable, primary-source-grounded shortlist. Rows are unranked, not a leaderboard."""

DATE = "2026-09-30"
PAPERS = {
    "thinklisten": "2510.07497",
    "flair": "2603.17837",
    "minicpm": "2604.27393",
    "step3": "2609.14005",
    "venus": "2609.13814",
    "duplexomni": "2606.09186",
    "voicechat": "2609.21967",
    "syncllm": "2409.15594",
    "moshi": "2410.00037",
    "duplexsla": "2605.20755",
    "adapt": "2609.29217",
    "synchrony": "2605.20356",
    "tauvoice": "2603.13686",
    "fdb3": "2604.04847",
    "echochain": "2604.16456",
    "mpe": "2609.31948",
    "mindpaced": "2510.09592",
    "contextspan": "2609.33443",
}
VENUES = {
    "thinklisten": ("ICLR", "2026", "https://proceedings.iclr.cc/paper_files/paper/2026/file/75c45fca2aa416ada062b26cc4fb7641-Paper-Conference.pdf"),
    "syncllm": ("EMNLP", "2024", "https://aclanthology.org/2024.emnlp-main.1192/"),
    "tauvoice": ("ICML", "2026", "https://proceedings.mlr.press/v306/ray26a.html"),
}

CATEGORIES = [
    {
        "id": "systems", "title": "Reasoning and system designs", "label": "tab:systems",
        "selection": "Seven anchors span explicit and latent listening-time reasoning, timed text-backbone speech, concurrent formulation/articulation, two asynchronous interaction/thinking designs, and native parallel text/function heads. Moshi is compared separately in the synchronization shortlist. The other three categories retain five entries each.",
        "headers": ["System / paper", "Reasoning, backbone and speech path", "Code / weights", "Training release"],
        "widths": [0.22, 0.43, 0.20, 0.15],
        "rows": [
            {"name": "Think while listening", "cite": "thinklisten", "cells": ["Moshi/Helium 7B temporal + depth transformers; parallel user/agent audio and text. Silent text reasoning is interleaved with ASR and answer text; completeness and preference supervision.", "Study-specific code/weights not located; released Moshi is a different checkpoint.", "Recipe only; full 1.8M-example spoken-CoT collection not located."], "links": []},
            {"name": "FLAIR", "cite": "flair", "cells": ["Qwen2.5-7B + streaming Parakeet encoder + autoregressive speech decoder. Listening steps feed a soft vocabulary-weighted latent embedding; full-context teacher trains a causal inference model.", "Dedicated implementation/checkpoint not located.", "ELBO/SFT recipe; full mixture not located."], "links": []},
            {"name": "MiniCPM-o 4.5", "cite": "minicpm", "cells": ["Qwen3-8B (~9B system). Omni-Flow serializes timed windows. Main LLM predicts text/listen decisions; a small Llama/S3 speech-token decoder and streaming flow decoder synthesize audio.", "Inference + realtime demo and weights; Apache-2.0.", "General fine-tuning tools; complete duplex recipe and mixture not established."], "links": [("Code", "https://github.com/OpenBMB/MiniCPM-V"), ("Weights", "https://huggingface.co/openbmb/MiniCPM-o-4_5")]},
            {"name": "StepAudio 3 Realtime", "cite": "step3", "cells": ["Step 3.7 Flash MoE (196B total/11B active) + AuT speech encoder. Two concurrent audio-LLM processes share parameters: private formulation and articulation, with playback-aware pacing and async tools.", "Report/project demos; Realtime code/weights not located. Earlier Step releases are not this model.", "Recipe; full training code/mixture not located."], "links": [("Project", "https://stepaudiollm.github.io/step-audio-3-realtime/")]},
            {"name": "Realtime-Venus", "cite": "venus", "cells": ["MiniCPM-o 4.5-derived 9B Audio/Omni frontend; causal 1 s chunks, persistent context, and an asynchronous backend. A harness returns backend text to the speaking frontend.", "Inference/harness + Audio/Omni weights; Apache-2.0. Demo integration is Omni-based.", "Methods; complete training package/mixture not located."], "links": [("Code", "https://github.com/inclusionAI/Realtime-Venus"), ("Weights", "https://huggingface.co/inclusionAI/Realtime-Venus")]},
            {"name": "DuplexOmni", "cite": "duplexomni", "cells": ["Qwen3-Omni Thinker/Talker interaction model; 480 ms slices and persistent speech context. A separate pluggable thinking layer returns streaming feedback and can be stopped. Reported full configuration uses Gemini-3.1-Flash-Lite.", "Inference, training and data-pipeline code; weights released. Source Apache-2.0; upstream terms apply.", "Writer-Director metadata + one generated shard; not the full ~9 TB corpus."], "links": [("Code", "https://github.com/MuyeHuang/DuplexOmni"), ("Weights", "https://huggingface.co/MuyeHuang/DuplexOmni"), ("Data", "https://huggingface.co/datasets/MuyeHuang/DuplexOmni-Data")]},
            {"name": "NemotronLabs VoiceChat", "cite": "voicechat", "cells": ["11B system: Nemotron Nano 9B v2 + 80 ms FastConformer features; parallel text/function heads, auxiliary RNN-T and separately trained streaming TTS. No user ASR transcript fed into the LLM. Tool execution currently disables barge-in.", "NeMo runtime branch + weights; OpenMDW-1.1 weights. Not a Moshi decoder.", "Training methods and sources; full pipeline and mixture not established."], "links": [("Code", "https://github.com/NVIDIA-NeMo/Speech/tree/nemotron-labs-voicechat"), ("Weights", "https://huggingface.co/nvidia/NVIDIA-NemotronLabs-VoiceChat-11B")]},
        ],
    },
    {
        "id": "synchronization", "title": "Synchronization and temporal interfaces", "label": "tab:synchronization",
        "selection": "Five directly relevant works cover clock-aligned serialization, codec-rate multi-stream generation, speech/listening/action alignment, adaptive scheduling, and representation-level speaker/listener coupling. The last is an analysis, not another model architecture.",
        "headers": ["Paper", "Temporal mechanism", "What it establishes", "Access / remaining issue"],
        "widths": [0.22, 0.30, 0.27, 0.21],
        "rows": [
            {"name": "SyncLLM", "cite": "syncllm", "cells": ["Llama 3-8B with deduplicated HuBERT units (25 Hz before deduplication); periodic speaker/chunk tokens align the sequence to a real-world clock. Speculative user chunks are replaced by observed input.", "Synchronous full-duplex scheduling despite variable token counts; evaluates processing/network delay.", "Official paper/demos; model code/weights not located. Clock alignment alone does not establish revision correctness."], "links": [("Project", "https://syncllm.cs.washington.edu/")]},
            {"name": "Moshi", "cite": "moshi", "cells": ["Mimi 12.5 Hz (80 ms) frames; temporal transformer plus depth transformer model parallel audio streams and aligned inner-monologue text.", "A concrete shared acoustic grid, streaming speech generation, and low-latency duplex interaction.", "Inference and fine-tuning code + weights. MIT/Apache code; model CC BY 4.0. A frame clock is not a semantic commitment policy."], "links": [("Code", "https://github.com/kyutai-labs/moshi"), ("Fine-tuning", "https://github.com/kyutai-labs/moshi-finetune"), ("Weights", "https://huggingface.co/kyutai/moshiko-pytorch-bf16")]},
            {"name": "DuplexSLA", "cite": "duplexsla", "cells": ["Step-Audio 2 mini-derived ~7B model. A 160 ms clock joins two 80 ms listening features, one text/four audio tokens, and up to ten action tokens; queued action spillover and dual-side ASR.", "Native concurrent speaking/listening plus timestamp-aligned planning, control and tool events.", "Official repository says inference, weights and benchmark are forthcoming. Not a released checkpoint as of cutoff."], "links": [("Release status", "https://github.com/hyzhang24/DuplexSLA")]},
            {"name": "AdaptDuplex", "cite": "adapt", "cells": ["Qwen3-Omni Thinker/Talker; 0.48/0.64/0.96 s windows, bounded text lead, and up to four indexed backend jobs. Cancelled/stale results are suppressed before injection.", "Adaptive granularity and explicit backend-result admission already exist; not a new idea to simply cancel a stale job.", "Paper verified; dedicated code/checkpoint not located. Joint speaker-owned state and actual playback still need controlled tests."], "links": []},
            {"name": "Synchronization and Turn-Taking", "cite": "synchrony", "cells": ["Moshi--Moshi appointment dialogues: lagged CKA compares speaker/listener hidden states; causal probes classify end-of-interpausal-unit hold/non-hold events.", "Representational coupling and predictive timing signals vary with noise and speech activity bias.", "Preprint; study artifacts not located. Restricted task; CKA/probe success is not causal reasoning consistency."], "links": []},
        ],
    },
    {
        "id": "benchmarks", "title": "Benchmarks for the proposal", "label": "tab:benchmarks",
        "selection": "Five complementary tests cover streaming reasoning onset, grounded task completion, natural disfluency/tool use, post-interruption state revision, and speaker/addressee control. Their scores should not be merged into a leaderboard.",
        "headers": ["Benchmark", "Coverage / provenance", "Useful measurements", "Availability / blind spot"],
        "widths": [0.22, 0.28, 0.25, 0.25],
        "rows": [
            {"name": "SRQA", "cite": "thinklisten", "cells": ["TTS/LLM-rewritten ARC-E/C, SIQA, PIQA, GSM8K; mostly single-turn synthetic spoken questions.", "Reasoning accuracy and post-question chain-of-thought delay; prefix sufficiency controls.", "Construction in ICLR paper; released audio/eval package not located. CoT onset is not first useful audible answer."], "links": []},
            {"name": "tau-Voice", "cite": "tauvoice", "cells": ["278 airline/retail/telecom tasks; clean/realistic speech; full-duplex simulated user. ICML 2026 (PMLR 306).", "Grounded pass@1, interruption behavior and voice interaction quality; tool/task consequences.", "Code/tasks/simulator; provider APIs needed. Virtual time decouples simulation from wall-clock runtime; pin original revision (repo now tau3-bench)."], "links": [("Code/tasks", "https://github.com/sierra-research/tau2-bench")]},
            {"name": "Full-Duplex-Bench v3", "cite": "fdb3", "cells": ["Human recordings, five disfluency types, chained tools across four task domains.", "Tool-selection F1, argument accuracy, pass@1; first response, tool and completion latencies.", "Scoring/inference code + recording download. Tool F1 is not task success; exact and judge-assisted argument scores differ."], "links": [("Code/data", "https://github.com/DanielLin94144/Full-Duplex-Bench/tree/main/v3")]},
            {"name": "EchoChain", "cite": "echochain", "cells": ["200 controlled interrupted conversations; synthesized user/barge-in audio; four closed realtime models; paired half-duplex control.", "Conversation/criterion pass rates and failures: contextual inertia, interruption amnesia, objective displacement.", "Paper, prompts and examples verified; standalone code/audio release not located. Does not cover backchannels, side speech or detailed acoustic timing."], "links": []},
            {"name": "Duplex-MPE", "cite": "mpe", "cells": ["2,000 matched pairs / 4,000 synthetic streams; 3--4 human roles plus assistant; explicit/implicit address.", "Response initiation, answer accuracy, silence preservation, floor release; speaker-owned update controls.", "Paper verified; standalone code/audio release not located. Floor release is conditional on the assistant already speaking."], "links": []},
        ],
    },
    {
        "id": "data", "title": "Training data and supervision sources", "label": "tab:data",
        "selection": "Five natural conversational resources are chosen for channel separation, temporal/speaker annotations, or task events. These are resources to construct supervision, not five existing reasoning-training mixtures.",
        "headers": ["Resource", "Scale / channels", "What is annotated", "Access / project use"],
        "widths": [0.20, 0.22, 0.28, 0.30],
        "rows": [
            {"name": "SmoothConv", "cite": "smoothconv", "cells": ["100.53 h; Chinese; natural multi-party, multi-channel audio.", "Expert transcripts, speaker IDs, turn state, timing and paralinguistic labels.", "HF release; CC BY-NC 4.0. Control/speaker supervision; shares source conversations with DuplexConv."], "links": [("Dataset card", "https://huggingface.co/datasets/qualialabsAI/SmoothConv")]},
            {"name": "DuplexConv", "cite": "duplexconv", "cells": ["2,000.21 h; Chinese; natural multi-party, multi-channel audio.", "LLM-assisted transcripts, per-track VAD, speaker/turn segments, acoustic and scene labels.", "HF release; CC BY-NC 4.0. Larger timing pretraining; audit labels and split by underlying source session."], "links": [("Dataset card", "https://huggingface.co/datasets/OpenT2S/DuplexConv")]},
            {"name": "otoSpeech Task", "cite": "ototask", "cells": ["20.006 h; 58 English sessions; two-speaker 48 kHz channels; seven task types.", "Synchronized events, stimuli, participant artifacts and task-related metadata.", "Gated HF files/contact acceptance; CC BY 4.0. Task-evidence alignment; verify outcomes before treating as reasoning labels."], "links": [("Dataset card", "https://huggingface.co/datasets/otoearth/otoSpeech-full-duplex-task-oriented-20h")]},
            {"name": "otoSpeech conversational", "cite": "otoconv", "cells": ["280 h raw / 141 h curated; English; separate speaker channels; curated 44.1 kHz.", "Session/speaker metadata, redactions, surveys; natural overlap and timing.", "Gated HF files/contact acceptance; CC BY 4.0. Listening robustness; curated hours are a subset, not extra data."], "links": [("Dataset card", "https://huggingface.co/datasets/otoearth/otoSpeech-full-duplex-processed-141h")]},
            {"name": "Open Yap 1K", "cite": "openyap", "cells": ["1,000 h; 1,602 English conversations; 239 speakers; separate 48 kHz channels.", "Word-level transcripts, speaker/device metadata, overlap and turn-gap statistics.", "Public sample; full corpus by request/Data Use Agreement. Natural conversation, not an ungated full release."], "links": [("Release/terms", "https://github.com/The-Agentic-Data-Co/open-yap-1k")]},
        ],
    },
]

DATA_AUTHORS = {"smoothconv": "QualiaLabs", "duplexconv": "OpenT2S", "ototask": "otoEarth", "otoconv": "otoEarth", "openyap": "The Agentic Data Company"}

GAPS = [
    {"id": "G1", "text": "Jointly measure evidence age, correct useful audible response time, and unsafe commitment under late corrections.", "closest": ["thinklisten", "echochain", "mindpaced"]},
    {"id": "G2", "text": "Maintain speaker-owned hypothesis versions across concurrent capture, reasoning, synthesis and playback.", "closest": ["moshi", "mpe", "synchrony"]},
    {"id": "G3", "text": "Establish causal end-to-end consistency across corrected frontend state, pending tools and output queues, beyond cancellation alone; distinguish VoiceChat's tool-execution listening restriction.", "closest": ["adapt", "venus", "contextspan", "duplexomni", "voicechat"]},
    {"id": "G4", "text": "Validate adaptive temporal interfaces against real wall-clock deadlines and compute contention, not only virtual-clock task scores.", "closest": ["syncllm", "minicpm", "duplexsla", "tauvoice"]},
    {"id": "G5", "text": "Construct auditable prefix-sufficiency, revision and addressee labels without future-evidence leakage or cross-corpus session contamination.", "closest": ["thinklisten", "flair", "fdb3", "mpe"]},
]

RQ = [
    {"id": "RQ1", "title": "Think while listening", "question": "When is partial speech sufficient to begin useful reasoning, and when should an emerging hypothesis remain provisional?", "proposal_link": "Semantic sufficiency and revision-aware partial-input supervision.", "hypothesis": "A trigger conditioned on available evidence and correction risk improves the correct-answer/latency frontier over end-of-turn and fixed-prefix triggers.", "method": "Predict prefix sufficiency from causal input and track hypothesis versions; allow private inference before authorizing a task-specific spoken claim.", "experiment": "200 matched late-constraint questions with two suffixes sharing an identical prefix; compare end-of-turn, fixed-prefix and calibrated triggers under the same evidence and decode budgets.", "metrics": "Correct useful audible response latency, final accuracy, premature-claim rate, calibration and unnecessary revisions.", "prior_work": ["thinklisten", "flair"], "distinction": "Early or latent reasoning while listening already exists; the candidate contribution is risk-calibrated revision under delayed/jittered evidence, not the concurrency claim itself."},
    {"id": "RQ2", "title": "Think while speaking", "question": "How far can reasoning and synthesis run ahead of playback without committing to an answer that new evidence will invalidate?", "proposal_link": "Time to the first useful response and robustness to self-correction.", "hypothesis": "Evidence-tagged output queues and a bounded playback lead reduce stale audible claims at matched response-quality and compute budgets.", "method": "Separate private formulation from articulation, annotate queued output with evidence/state dependencies, revalidate unplayed output and repair already audible claims.", "experiment": "Deliver a correction before generation, during synthesis, while queued, or after playback; compare unrestricted lead, fixed-duration lead and evidence-aware admission.", "metrics": "Stale audible duration, useful-response latency, output underruns, repetition and repair success.", "prior_work": ["mindpaced", "step3", "adapt", "echochain"], "distinction": "Dual-process reasoning and bounded lead already exist. Test an explicit causal playback commitment boundary, rather than merely producing a faster first sound."},
    {"id": "RQ3", "title": "Listen while speaking", "question": "Can new input update the right speaker/task hypothesis while the system speaks, without mistaking backchannels or side conversations for corrections?", "proposal_link": "Speaker/stream-aware listening and evidence integration across turns.", "hypothesis": "Per-speaker evidence watermarks and selective state invalidation improve correction accuracy without increasing needless interruption or side-speech responses.", "method": "Prioritize fresh input ingestion under generation load; associate updates with speaker, addressee, task and hypothesis versions before invalidating dependent output.", "experiment": "Use matched corrections, backchannels and other-directed utterances with oracle versus predicted speaker/addressee labels; compare global versus speaker-owned state under matched load.", "metrics": "Correction accuracy, evidence staleness, false interruption, silence preservation and task completion.", "prior_work": ["mpe", "synchrony", "venus"], "distinction": "Turn-taking and addressee tests are not new. The candidate is their coupling to causal reasoning-state ownership; attribution noise must be separated from reasoning failure."},
    {"id": "RQ4", "title": "Synchronize listening, reasoning and speaking", "question": "Which temporal interface remains reliable when speaking rate, inference speed, network delay and backend latency vary independently?", "proposal_link": "Streaming latent state, uncertainty, and response preparation under partial evidence.", "hypothesis": "A scheduler observing evidence age and audio-buffer duration has fewer missed deadlines and stale claims than fixed-window scheduling at matched task accuracy.", "method": "Expose input watermarks, deadlines and predicted audio lead to the controller; adapt ingestion/generation quantum without using future speech or privileging one arm's compute.", "experiment": "Replay identical dialogues across speech-rate, jitter and compute-contention conditions; compare fixed 80 ms/1 s interfaces where implementable with a two- or three-level adaptive controller.", "metrics": "p50/p95 event-to-ingestion and correct-useful-response delays, buffer underruns, deadline misses, quality and GPU-seconds.", "prior_work": ["syncllm", "moshi", "minicpm", "duplexsla", "adapt", "tauvoice"], "distinction": "Fixed clocks, adaptive windows and action alignment already exist. The target is a causal consistency/robustness claim under heterogeneous clocks; virtual-time results alone are insufficient."},
    {"id": "RQ5", "title": "Revise while delegating", "question": "What should be canceled, reused or withheld when a speaker correction arrives between backend launch, result return and audible delivery?", "proposal_link": "Revision-aware hypotheses and late-arriving constraints; extension to modern asynchronous systems.", "hypothesis": "Speaker/task-versioned dependency checks at both result admission and playback reduce stale-answer failures beyond an existing cancellation-only baseline.", "method": "Tag jobs/results and output segments with dependencies, reject invalidated results, and recompute only affected work; use read-only or simulated tools in the pilot.", "experiment": "Inject corrections into a simulated 0.5/2/5 s backend at launch, inflight, return and pre-playback stages; compare blind injection, explicit cancel/stale suppression, and joint result/output validation.", "metrics": "Task success, stale-result use, wasted backend work, repair latency and unnecessary cancellation.", "prior_work": ["venus", "adapt", "contextspan", "duplexomni", "voicechat", "fdb3", "tauvoice"], "distinction": "AdaptDuplex cancels jobs and suppresses stale results; DuplexOmni stops/resets background thinking. VoiceChat's tool-execution barge-in restriction is a separate baseline condition. Candidate novelty requires speaker-specific dependency plus audible-commitment consistency, not renaming cancellation."},
]

# Eight concrete, unranked candidates, grouped under five report questions.
IDEA_SPECS = [
    ("I1", "RQ1", "Calibrated prefix sufficiency under late constraints", "Trigger private reasoning from causal prefix sufficiency and correction risk.", "method", ["G1", "G5"], "12--24 GPU-hours", "Small calibration head / inference controller; no foundation pretraining.", "A sufficiency estimator may merely learn question-length or TTS cues.", "Either a better latency/accuracy frontier or a measured limit on prefix-only calibration."),
    ("I2", "RQ2", "Evidence-aware playback commitment fence", "Admit task-specific output only while its evidence dependencies remain valid.", "system", ["G1", "G2"], "8--20 GPU-hours", "Instrument text, synthesis and playback queues and dependency tags.", "Word/audio boundaries and mutable decoder state may prevent selective cancellation.", "Quantify whether queue-level revalidation reduces stale audible claims."),
    ("I3", "RQ2", "Correction-aware bounded articulation lead", "Adapt unplayed speech duration to correction risk rather than a token-count limit.", "method", ["G1", "G4"], "8--20 GPU-hours", "Duration estimator plus two- or three-level queue cap.", "Short buffers may trade false commitments for stutter/underruns.", "A commitment/latency/fluency Pareto curve, including negative results."),
    ("I4", "RQ3", "Listening freshness under speaking load", "Reserve ingestion capacity to keep new evidence from becoming stale during generation.", "system", ["G2", "G4"], "6--16 GPU-hours", "Instrument ingested-input watermarks and scheduler priorities.", "Freshness may be dominated by encoder lookahead rather than scheduler priority.", "Identify whether contention or intrinsic lookahead limits correction responsiveness."),
    ("I5", "RQ3", "Speaker-owned revision states", "Invalidate only hypotheses and output that depend on the speaker's relevant correction.", "method", ["G2", "G5"], "12--28 GPU-hours", "First oracle identities, then predicted diarization/addressee labels.", "Attribution mistakes may erase any gain from state separation.", "Decompose attribution errors versus stale shared-reasoning errors."),
    ("I6", "RQ4", "Evidence-age-aware adaptive temporal quantum", "Adapt chunk duration using evidence age, playback budget and compute deadlines.", "method", ["G4"], "8--24 GPU-hours", "Controller around a released streaming runtime; fixed feature extractors.", "Changing quantum can mismatch the model's training protocol.", "Measure robustness boundaries rather than claiming universal adaptivity."),
    ("I7", "RQ5", "Joint backend-result and output dependency validation", "Check state dependencies both when a job returns and before its answer becomes audible.", "system", ["G2", "G3"], "8--20 GPU-hours", "Versioned read-only/simulated jobs; cancellation baseline explicitly included.", "This duplicates AdaptDuplex unless joint speaker/output dependencies add measurable value.", "Determine whether a second commitment-stage check improves corrected task success."),
    ("I8", "RQ4", "Virtual-time versus wall-clock consistency audit", "Compare identical task traces under virtual replay and physical inference/playback time.", "analysis", ["G1", "G4"], "4--12 GPU-hours", "Timestamped trace harness, controlled delay and queue instrumentation.", "Provider/runtime differences may confound the timing comparison.", "Expose which conclusions survive real deadlines and which are simulator artifacts."),
]

EXTRA_URLS = [link[2] for link in VENUES.values()] + [
    "https://github.com/ICLR/Master-Template/tree/master/iclr2026",
    "https://iclr.cc/Conferences/2026/AuthorGuide",
    "https://github.com/stepfun-ai/Step-Audio-R1",
    "https://huggingface.co/stepfun-ai/Step-Audio-R1.1",
]
