"""Curated source facts and explicitly labeled synthesis, checked 2026-09-30.

Edit this file, then run scripts/build_site.py. No network or packages required.
The builder replaces bibliographic seed fields with audited arXiv metadata.
Paper existence and release availability are separate claims.
"""

DATE = '2026-09-30'
INSTRUCTION = "Read the proposal in ./proposals/original. It's a little outdated, and our task for today is to do a literature review and draft a project page (with only the literature review tab) that has a similar style of https://borrisonxiao.github.io/jsalt26-downsampling. I have read the StepAudio 3 Realtime's technical report, and I am reading tau-voice and miniCPM-o papers. However, I think we need more latest architectures of the modern duplex models. Do the literature review on both the system designs, whether they are open-sourced, as well as any available training data and benchmarks (like tau-voice, etc.). It would be nice if we can have some tables for each category, e.g., systems, benchmarks, training data, etc., so that we can easily compare different sources features (for instance, this paper https://proceedings.iclr.cc/paper_files/paper/2026/file/75c45fca2aa416ada062b26cc4fb7641-Paper-Conference.pdf is using Moshi, but there are other designs that use LLM as decoders, etc.). Now do the review, and draft a page and push to git@github.com:BorrisonXiao/ai2ai-duplex-report.git. I will change the page setting when you are done (note that you should put a link to the webpage in the README, actually upate this rule in the skill if applicable, another rule is that do NOT manually break the lines in the report, let the browser adjust)."
SCOPE = 'Incremental, revision-aware and speaker-aware reasoning in full-duplex spoken dialogue, emphasizing 2024–September 2026 primary papers and usable research artifacts.'
QUESTIONS = [
    'How do concurrent input, text, speech output and interaction control share time and parameters?',
    'Where does private reasoning run, and can new speech revise it?',
    'Which code, checkpoints, fine-tuning recipes and training corpora are actually released?',
    'Which benchmarks measure timing, corrections, speaker attribution and grounded task completion?',
    'Which natural or synthetic datasets preserve channels, overlap, timestamps and task state?',
    'Which parts of the March proposal are established prior work, and which questions remain open?',
]

SYSTEMS = []
def system(id, name, title, authors, date, venue, family, backbone, stream, decoder, control, result, relevance, limitation, code=None, weights=None, training='Not located', data='Full training mixture not located', license='Consult component licenses', extra=None):
    SYSTEMS.append(dict(id=id, name=name, title=title, authors=authors, date=date, venue=venue, family=family, backbone=backbone, stream=stream, decoder=decoder, control=control, result=result, relevance=relevance, limitation=limitation, code=code, weights=weights, training=training, data=data, license=license, extra=extra or []))

system('2609.14005', 'StepAudio 3 Realtime', 'StepAudio 3 Realtime Technical Report', 'Bin Lin et al. / StepFun-Audio Team', '2026-09-12', 'Technical report / preprint', 'Text backbone', 'Step 3.7 Flash MoE: 196B total / 11B active', 'AuT encoder + adapter; user and model audio feed shared conversational context.', 'Streaming speech generator; detailed generator internals are less specified than the LLM.', 'Listen / speak / start / end states; private think-while-speaking; asynchronous tools.', 'Authors report 98.9 Overall on Artificial Analysis Full-Duplex Bench and 56.0% macro task success on τ-Voice.', 'Strong reference for coordinating speech, private reasoning and tool execution.', 'Reported benchmark scores use their own protocol. No StepAudio 3 Realtime checkpoint or training release was located; earlier Step-Audio releases are separate models.', code=('API / project demos', 'https://stepaudiollm.github.io/step-audio-3-realtime/'), training='Recipe described; code not located', license='Realtime release terms not established', extra=[('Provider', 'https://platform.stepfun.com/')])
system('2604.27393', 'MiniCPM-o 4.5', 'MiniCPM-o 4.5: Towards Real-Time Full-Duplex Omni-Modal Interaction', 'Junbo Cui et al.', '2026-04-30', 'Technical report / preprint', 'Text backbone', 'Qwen3-8B; about 9B total', 'Omni-Flow serializes time windows of audio, video and assistant output; [listen] when silent.', 'Small Llama speech-token decoder + S3 tokens + streaming flow-matching waveform decoder.', 'Explicit listen/speak decision; main LLM generates text, separate decoder generates speech.', 'In the paper’s ablation, 1.0 s windows outperform 0.1 / 0.2 s on the tested language tasks.', 'Concrete open alternative to Moshi for a streaming encoder + text reasoning backbone.', 'Shorter windows trade response opportunity against language competence. A full duplex-training mixture is not released.', code=('Inference / realtime demo', 'https://github.com/OpenBMB/MiniCPM-V'), weights=('9B weights', 'https://huggingface.co/openbmb/MiniCPM-o-4_5'), training='General fine-tuning tools; full duplex recipe not established', license='Apache-2.0 code and weights')
system('2609.13814', 'Realtime-Venus', 'Realtime-Venus: A full-duplex interaction system with asynchronous delegation', 'Venus Team, Ant Group / Tsinghua University', '2026-09-12', 'Technical report / preprint', 'Delegated', 'MiniCPM-o 4.5-derived Audio and Omni frontends; 9B family', 'One-second causal chunks; retained frontend state; separate background task loop.', 'Frontend text and speech generation; text results admitted back into the stream.', 'Explicit foreground / delegation outputs; harness executes background jobs asynchronously.', 'Audio variant reports continuation of 97% / 88% / 86% for backchannel / other-directed / background speech in FDB v1.5.', 'Released architecture and harness for testing revisions while a backend task is pending.', 'Audio and Omni evaluations differ. Released harness/demo integration is Omni-based; do not assume every paper setting is reproduced.', code=('Omni integration + Harness', 'https://github.com/inclusionAI/Realtime-Venus'), weights=('Audio + Omni checkpoints', 'https://huggingface.co/inclusionAI/Realtime-Venus'), training='Training method described; full training code not located', license='Apache-2.0 release; separate third-party notices')
system('2609.21967', 'NemotronLabs VoiceChat', 'NemotronLabs VoiceChat: An Open Full-duplex Speech-to-Speech Model with Tool Calling Capabilities', 'Jagadeesh Balam et al.', '2026-09-18', 'Technical report / preprint', 'Text backbone', 'Nemotron Nano v2 9B; about 11B system', '600M streaming FastConformer; parallel agent-text and function-call channels; auxiliary RNN-T transcript.', 'Separately trained streaming TTS with causal codec and acoustic decoder.', 'Learned streaming turn control and native structured tool output.', 'Reports 82.5% tool-selection F1 on FDB v3; tool arguments and full execution remain weaker.', 'Open encoder–LLM system with distinct transcript, reply and tool streams.', 'Card/paper explicitly limit barge-in during tool execution, context length and noisy-speech robustness.', code=('Inference / runtime branch', 'https://github.com/NVIDIA-NeMo/Speech/tree/nemotron-labs-voicechat'), weights=('11B weights', 'https://huggingface.co/nvidia/NVIDIA-NemotronLabs-VoiceChat-11B'), training='Recipe documented; complete training pipeline not established', license='Weights: OpenMDW 1.1; code: repository terms')
system('2609.19334', 'NVIDIA frontend–backend', 'A frontend-backend architecture for tool calls in full-duplex speech models', 'Ke Hu et al.', '2026-09-16', 'Preprint', 'Delegated', 'Nemotron-Nano-9B frontend; interchangeable text backend', 'Duplex speech-to-text frontend emits delegation token and forwards streaming transcription.', 'Natural-language backend result enters frontend by prefill-and-repeat, then streaming TTS.', 'Backend executes tools; frontend output is suppressed during execution in this implementation.', 'Authors report 92–97% tool-call recall; recall is different from argument correctness or task success.', 'Makes backend delegation and result injection concrete for a revision-aware system.', 'A modular design does not guarantee continued interaction during tool use. No separate reproducible model package was located.', code=('Demo', 'https://huggingface.co/spaces/frontend-backend-duplex/demo'), training='Method documented; dedicated release not located')
system('2609.29217', 'AdaptDuplex', 'AdaptDuplex: from static to adaptive full-duplex spoken dialogue', None, '2026-09-24', 'Preprint', 'Text backbone', 'Qwen3-Omni-30B-A3B-Instruct Thinker–Talker', 'Canonical per-window protocol; variable-duration windows and bounded text lead.', 'Talker consumes queued text conditions to generate codec tokens; resets on turn end.', 'Explicit behavior tokens; training-free control by logits bias; progressive alignment training.', 'Reports 72.9 Final score on HumDial-FDBench; interruption and rejection have separate trade-offs.', 'Very recent alternative for controlling the timing/capacity trade-off.', 'Paper verified; trained checkpoint and training package not located at the review cutoff.', training='Recipe described; released implementation not established')
system('2607.06540', 'Lychee-FD', 'Hierarchical Acoustic-Semantic Modeling: Modality Separation and Semantic Coherence for Full-Duplex SLMs', 'Zhenyu Liu et al.', '2026-07-07', 'ACL 2026; linked arXiv manuscript', 'Parallel codec', 'StepAudio-2-mini initialization', 'Streaming encoder; shared shallow layers; parallel semantic, acoustic and control heads.', '25 Hz CosyVoice2 speech-token channel; semantic alignment channel.', 'Deep parameter separation and dense semantic supervision target acoustic/text gradient conflict.', 'Paper reports semantic retention and duplex improvements; repository releases serving and domain fine-tuning code.', 'Useful open native multi-stream comparison when reasoning degrades after speech adaptation.', 'Shared-parameter interference is empirically studied in these models, not proven inevitable for all architectures.', code=('Serving + training package', 'https://github.com/HITsz-TMG/Lychee-FD'), weights=('Lychee-FD checkpoint', 'https://huggingface.co/HIT-TMG/Lychee-FD'), training='Released Training_package for domain-specific fine-tuning', license='Apache-2.0; external vocoder has its own terms', extra=[('Training package', 'https://github.com/HITsz-TMG/Lychee-FD/tree/main/Training_package')])
system('2606.14528', 'BayLing-Duplex', 'BayLing-Duplex: Native Full-Duplex Speech Dialogue with a Single Autoregressive LLM', 'Qingkai Fang, Shoutao Guo, Yang Feng', '2026-06-12', 'Preprint', 'Serialized tokens', 'GLM-4-Voice / GLM-4-9B', 'User speech, assistant text and assistant speech interleaved in 10:5:10 blocks.', 'LLM predicts text and speech tokens; GLM flow-matching decoder renders speech.', 'Four vocabulary control tokens encode silence and response boundaries; no auxiliary control head.', '400K duplex SFT samples + DPO; authors report 92% turn-taking and 100% interruption success on InstructS2S-Eval.', 'A direct example of duplex decisions implemented as ordinary autoregressive token prediction.', '0.8 s block granularity constrains response opportunities. The reported results do not establish private reasoning revision.', code=('Duplex inference', 'https://github.com/BayLing-Models/BayLing-Duplex'), weights=('GLM-derived weights', 'https://huggingface.co/BayLing-Models/BayLing-Duplex'), training='Inference package; full training recipe code not located', license='Repository / GLM component terms')
system('2606.09186', 'DuplexOmni', 'DuplexOmni: Real-Time Listening, Seeing, Thinking, and Speaking for Full-Duplex Interaction', 'Muye Huang et al.', '2026-06-08', 'Preprint', 'Delegated', 'Qwen3-Omni-derived interaction model + thinking backend', 'Streaming audio/video interaction layer; reasoning and tool layer run in parallel.', 'Interaction model streams text and speech while incorporating backend results.', 'Separates fast conversational behavior from slower reasoning/tool work.', 'Reports full-duplex and multimodal evaluations; code, weights and a partial training artifact are linked.', 'Research-ready two-layer design with an explicit data-generation and training framework.', 'Full trainable dataset is described as about 9 TB; release contains metadata and one generated shard, not the entire corpus.', code=('Pipeline + training + runtime', 'https://github.com/MuyeHuang/DuplexOmni'), weights=('Model weights', 'https://huggingface.co/MuyeHuang/DuplexOmni'), training='Training_framework and data_pipeline released', data='Metadata + one generated parquet shard; full corpus reconstructed', extra=[('Training data artifact', 'https://huggingface.co/datasets/MuyeHuang/DuplexOmni-Data')])
system('2510.07497', 'Think while listening', 'Can Speech LLMs Think while Listening?', 'Yi-Jen Shih et al.', '2025-10-08', 'ICLR 2026', 'Parallel codec', 'Moshi / Helium 7B + Mimi', 'Text monologue interleaves streaming ASR, silent text CoT and answer text alongside audio.', 'Moshi temporal + depth transformers; reasoning tokens have no corresponding spoken output.', 'Question-completeness supervision starts CoT early; correctness and length DPO improve adaptation.', 'Authors report 2.4× mean reasoning accuracy over Moshi and about 70% lower reasoning latency without accuracy loss.', 'Direct prior work for both semantic sufficiency and revision-aware reasoning in the original proposal.', 'Single-turn spoken reasoning suite; 480 ms ASR look-ahead; benchmark/model release not located. Reasoning latency is not first useful spoken answer latency.', training='Detailed appendix; code/checkpoint not located', extra=[('ICLR proceedings paper', 'https://proceedings.iclr.cc/paper_files/paper/2026/file/75c45fca2aa416ada062b26cc4fb7641-Paper-Conference.pdf')])
system('2602.06053', 'PersonaPlex', 'PersonaPlex: Voice and Role Control for Full Duplex Conversational Speech Models', 'Rajarshi Roy et al.', '2026-01-14', 'Preprint', 'Parallel codec', 'Moshi / Helium 7B', 'Concurrent user audio, assistant text and assistant audio; text role and voice prompts.', 'Moshi-family temporal/depth speech decoder with voice conditioning.', 'Learns duplex timing and persona-conditioned responses from real and synthetic conversations.', 'Paper evaluates role adherence, voice similarity and conversational timing.', 'Strong released Moshi-family control condition; persona control differs from speaker-specific reasoning.', 'Code and weights are available, but the complete paired-prompt conversation corpus was not located.', code=('Inference + browser demo', 'https://github.com/NVIDIA/personaplex'), weights=('7B weights; license acceptance', 'https://huggingface.co/nvidia/personaplex-7b-v1'), training='Full fine-tuning recipe not located', license='Code MIT; weights NVIDIA Open Model License')
system('2410.00037', 'Moshi', 'Moshi: a speech-text foundation model for real-time dialogue', 'Alexandre Défossez et al.', '2024-09-17', 'Technical report / preprint', 'Parallel codec', 'Helium 7B text LM + Mimi codec', 'Synchronized user-audio, assistant-audio and assistant-text streams at 12.5 Hz.', 'Temporal transformer models time; depth transformer predicts residual codec levels.', 'Text inner monologue precedes acoustic generation; learned silence and overlap patterns.', 'Paper reports 160 ms theoretical and approximately 200 ms practical latency under its setup.', 'Open foundation for the supplied paper; it already uses a pretrained LLM backbone.', 'Frame timing limits text bandwidth; basic inner monologue is not a private reasoning implementation.', code=('Python / Rust / MLX inference', 'https://github.com/kyutai-labs/moshi'), weights=('Moshiko + Mimi', 'https://huggingface.co/kyutai/moshiko-pytorch-bf16'), training='Official moshi-finetune package', license='Code MIT / Apache-2.0; weights CC BY 4.0', extra=[('Fine-tuning', 'https://github.com/kyutai-labs/moshi-finetune')])
system('2411.00774', 'Freeze-Omni', 'Freeze-Omni: A Smart and Low Latency Speech-to-speech Dialogue Model with Frozen LLM', 'Xiong Wang et al.', '2024-11-01', 'Preprint', 'Text backbone', 'Frozen Qwen2-7B-Instruct', 'Chunked streaming encoder feeds a frozen text backbone.', 'Separate streaming autoregressive speech decoder; prefix adaptation.', 'Chunk-level state classifier manages user interruption; model-server scheduling.', 'Reports training with paired speech/text and 60K multi-round text QA examples.', 'A low-data comparison for retaining the backbone’s language competence.', 'Control uses a classifier and scheduling machinery; frozen parameters do not alone prove robust incremental reasoning.', code=('Inference + server demo', 'https://github.com/VITA-MLLM/Freeze-Omni'), weights=('Speech modules + external Qwen', 'https://huggingface.co/VITA-MLLM/Freeze-Omni'), training='Inference release; full training code not located')
system('2410.17799', 'OmniFlatten', 'OmniFlatten: An End-to-end GPT Model for Seamless Voice Conversation', 'Qinglin Zhang et al.', '2024-10-23', 'ACL 2025', 'Serialized tokens', 'GPT-style text backbone', 'Flattening serializes speech/text and chunked duplex turns into one causal token sequence.', 'Backbone predicts text and speech within the shared vocabulary.', 'Modality alignment → half-duplex → full-duplex progressive post-training.', 'Published method demonstrates duplex behavior without modifying the GPT backbone architecture.', 'Foundational reference for serialized-stream designs; helps contrast against Moshi’s parallel channels.', 'Public project provides demos; model/training artifacts not located.', code=('Project demos', 'https://omniflatten.github.io/'), training='Paper recipe only', license='No code/weight release established', extra=[('ACL paper', 'https://aclanthology.org/2025.acl-long.709/')])
system('2505.02707', 'Voila Autonomous', 'Voila: Voice-Language Foundation Models for Real-Time Autonomous Interaction and Voice Role-Play', 'Yemin Shi et al.', '2025-05-05', 'Preprint', 'Parallel codec', 'Hierarchical multi-scale voice-language transformer', 'Multi-scale text and acoustic processing with autonomous listen/respond behavior.', 'Hierarchical speech generation; speaker conditioning supports voice and role control.', 'Autonomous full-duplex variant is released separately from turn-based Chat.', 'Authors report 195 ms response latency; released Voila Benchmark covers spoken knowledge/reasoning.', 'Released alternative to Moshi with explicit autonomous checkpoint.', 'Use Voila-autonomous-preview for duplex experiments; Chat/base releases alone do not imply duplex.', code=('Inference', 'https://github.com/maitrix-org/Voila'), weights=('Autonomous preview', 'https://huggingface.co/maitrix-org/Voila-autonomous-preview'), training='Full pretraining / duplex training recipe not located', license='Code MIT; checkpoint terms per model card')
system('2505.17060', 'SALMONN-omni', 'SALMONN-omni: A Standalone Speech LLM without Codec Injection for Full-duplex Conversation', 'Wenyi Yu et al.', '2025-05-17', 'Preprint (reviewed version)', 'Text backbone', 'Single text LLM + streaming speech modules', 'Streaming encoder supplies continuous embeddings rather than codec tokens to the LLM vocabulary.', 'Streaming speech synthesizer conditions on LLM representations.', 'Dynamic thinking/state mechanism; preference optimization improves interaction control.', 'Authors report at least 30% relative improvement over evaluated open duplex baselines on their speech tasks.', 'Important distinction: codec-free LLM vocabulary does not mean no codec anywhere in synthesis.', 'The SALMONN family repository links demos and other model releases; an omni-specific code/weight release was not established.', code=('Family repo / omni demos', 'https://github.com/bytedance/SALMONN'), training='Omni-specific training release not located', license='Omni release terms not established')
system('2505.15670', 'SALM-Duplex', 'SALM-Duplex: Efficient and Direct Duplex Modeling for Speech-to-Speech Language Model', 'Ke Hu et al.', '2025-05-21', 'Interspeech 2025', 'Parallel codec', 'TinyLlama-1.1B + 100M streaming encoder', 'Continuous user embeddings fused with agent text/audio channels.', 'Agent codec tokens; personalized NanoCodec at 0.6 kbps.', 'Direct simultaneous channel modeling; skips additional speech pretraining.', 'Authors report better dialogue/turn behavior than evaluated duplex baselines with a smaller backbone.', 'Early continuous-input design that avoids tokenizing both audio directions identically.', 'Paper claims training/inference release; exact current legacy checkpoint mapping was not verified.', training='Authors report release; exact artifact mapping unconfirmed', data='Synthetic duplex recipe described; full mixture not established', extra=[('Published paper', 'https://www.isca-archive.org/interspeech_2025/hu25f_interspeech.html')])
system('2609.33443', 'Context Spanning', 'Context Spanning: A Communication Framework for Full-Duplex Speech Models and External LLM Backends', 'Seonghyeon Go et al.', '2026-09-27', 'Preprint; submitted to ICASSP 2027', 'Delegated', 'Moshi frontend + external text backend', 'Backend text injected into duplex token frames through chunked causal prefill.', 'Frontend independently produces speech after receiving raw reference text.', 'Context injection must fit prefill + one decode step in an 80 ms frame budget.', 'Reports QA and full-duplex evaluations with direct information injection.', 'Fresh alternative to compressed backend conditioning; useful for evidence provenance.', 'Very recent preprint. Some experiments use precomputed backend answers with fixed delay; that differs from live tool execution.', training='Method described; dedicated code/checkpoint not located')
system('2609.34461', 'CharDuplex / FDGym', 'CharDuplex: Building Character-Consistent Full-Duplex Spoken Dialogue Models', 'Donghang Wu et al.', '2026-09-28', 'Preprint', 'Parallel codec', 'GLM-4-Voice adapted to always-on dual streams', 'Time-aligned user and assistant streams; character descriptions condition dialogue.', 'GLM speech generation with duplex adaptation.', 'Character SFT followed by interactive GRPO with an LLM user simulator in FDGym.', 'Reports the highest mean SpeechRole-Eval score among its evaluated open-model baselines.', 'Illustrates interactive rollout training rather than fixed prerecorded conversation supervision.', 'Persona consistency is different from speaker attribution or correct reasoning revisions; release artifacts not located.', training='FDGym recipe documented; code/checkpoint not located')

BENCHMARKS = [
    dict(id='2603.13686', name='τ-Voice', authors='Soham Ray, Keshav Dhandhania, Victor Barres, Karthik Narasimhan', date='2026-03-14', venue='Preprint', scope='278 airline / retail / telecom tasks; clean and realistic accents/noise; simulated full-duplex user.', metrics='Grounded pass@1; latency, interruptions and voice interaction quality.', access='Code + domain tasks + simulator; model/TTS APIs required. Current repo is τ³-bench.', use='End-to-end task completion and correction consequences.', caveat='Pin the task revision and simulator/provider configuration. Paper-clean, realistic and macro-domain scores are different conditions.', paper='https://arxiv.org/abs/2603.13686', artifact='https://github.com/sierra-research/tau2-bench', result='Original study reports voice-task success below its text baseline under both audio conditions.'),
    dict(id='2503.04721', name='Full-Duplex-Bench v1', authors='Guan-Ting Lin et al.', date='2025-03-06', venue='Preprint', scope='Controlled pause, backchannel, turn transition and user interruption scenarios.', metrics='Takeover / continuation / response timing and response quality by scenario.', access='Evaluation code and static data released.', use='Basic conversational timing regression suite.', caveat='Coarse timing/interaction evaluation does not establish reasoning or real tool execution.', paper='https://arxiv.org/abs/2503.04721', artifact='https://github.com/DanielLin94144/Full-Duplex-Bench/tree/main/v1_v1.5', result='Establishes automatic scenario-specific duplex behavior metrics.'),
    dict(id='2507.23159', name='Full-Duplex-Bench v1.5', authors='Guan-Ting Lin et al.', date='2025-07-30', venue='Preprint', scope='User interruption, listener backchannel, side conversation and ambient speech overlap.', metrics='Continue or yield appropriately; interruption response quality and timing.', access='Code + overlap data and metadata released.', use='Distinguish meaningful barge-in from other-directed/background speech.', caveat='Good overlap rejection alone does not prove correct speaker-conditioned reasoning.', paper='https://arxiv.org/abs/2507.23159', artifact='https://github.com/DanielLin94144/Full-Duplex-Bench/tree/main/v1_v1.5', result='Separates several overlap types that require different assistant actions.'),
    dict(id='2510.07838', name='Full-Duplex-Bench v2', authors='Guan-Ting Lin et al.', date='2025-10-09', venue='Preprint; updated framework 2026', scope='Live automated examiner; daily, correction, entity tracking and safety tasks; Fast / Slow pacing.', metrics='Turn fluency, multi-turn instruction following and task competence.', access='Streaming WebRTC/WebSocket orchestrator + task/examiner code released.', use='Dynamic corrections and long dialogue state.', caveat='Examiner and judge choices affect results; keep versions and prompts fixed.', paper='https://arxiv.org/abs/2510.07838', artifact='https://github.com/DanielLin94144/Full-Duplex-Bench/tree/main/v2', result='Reveals correction handling and entity-tracking failures in multi-turn systems.'),
    dict(id='2604.04847', name='Full-Duplex-Bench v3', authors='Guan-Ting Lin, Chen Chen, Zhehuai Chen, Hung-yi Lee', date='2026-04-06', venue='Preprint', scope='Real human audio; five disfluency types; chained tool calls in four task domains.', metrics='Tool selection F1, argument accuracy, pass@1, first response / tool / completion latency.', access='Inference/scoring code + released recording download.', use='Self-corrections, hesitation and multi-step tool reasoning.', caveat='Tool-selection F1 is not task completion. Judge-assisted and exact argument matching differ.', paper='https://arxiv.org/abs/2604.04847', artifact='https://github.com/DanielLin94144/Full-Duplex-Bench/tree/main/v3', result='Authors identify self-correction and hard multi-step reasoning as recurring failures.'),
    dict(id='2511.10262', name='MTR-DuplexBench', authors='He Zhang et al.', date='2025-11-13', venue='Findings of ACL 2026', scope='Multi-round full-duplex conversations with explicit continuous-dialogue segmentation.', metrics='Conversation behavior, dialogue quality, instruction following and safety.', access='Code + data linked in official repository.', use='Persistence of dialogue state and quality across rounds.', caveat='Segmentation/ASR choices influence turn-wise scoring; not a direct semantic-sufficiency label.', paper='https://arxiv.org/abs/2511.10262', artifact='https://github.com/ZhangHe0918/MTR-DuplexBench', result='Shows uneven performance across rounds and evaluation dimensions.'),
    dict(id='2507.19040', name='FD-Bench', authors='Yizhou Peng et al.', date='2025-07-25', venue='Interspeech 2025', scope='293 simulated conversations, 1,200 interruptions, over 40 h of generated speech.', metrics='Response/interrupt delay, WER, BLEU, coherence and generated-response quality.', access='Code + generation recipe + HF audio input dataset.', use='Server/client testing and interruption timing.', caveat='Independent of Full-Duplex-Bench; generated conversation audio is not natural human supervision.', paper='https://arxiv.org/abs/2507.19040', artifact='https://github.com/pengyizhou/FD-Bench', result='Provides repeated interruption evaluation of Moshi, Freeze-Omni and VITA-1.5.'),
    dict(id='humdial', name='HumDial Track 2 / FDBench', authors='ASLP-lab and challenge organizers', date='2026-01-01', venue='ICASSP 2026 challenge; date denotes challenge year', scope='English/Chinese human recordings; interruption versus rejection, including third-party speech.', metrics='Interruption accuracy, rejection accuracy, delays and challenge aggregate.', access='Official evaluation code and challenge data links; training split exceeds 107 h.', use='Interaction controller and real-recording robustness.', caveat='Track 1 emotional intelligence is a different dataset. Respect official train/dev/test splits.', paper=None, artifact='https://github.com/ASLP-lab/Hum-Dial', result='Pairs interruption and rejection rather than rewarding indiscriminate response.'),
    dict(id='2609.31948', name='Duplex-MPE', authors='Chengqian Ma et al.', date='2026-09-25', venue='Preprint', scope='2,000 matched scenario pairs / 4,000 streams; 3–4 human roles plus an assistant; explicit versus implicit address.', metrics='Fresh response initiation, answer accuracy, silence preservation and floor release.', access='Paper verified; standalone code/audio release not located.', use='Closest recent benchmark for the proposal’s multi-party speaker/stream-aware goal.', caveat='Scenario roles do not imply natural human recordings. Floor release depends on whether the model was speaking.', paper='https://arxiv.org/abs/2609.31948', artifact=None, result='Shows that frequent speech can coexist with wrong answers and failures to remain silent.'),
    dict(id='srqa', name='SRQA from Think while listening', authors='Yi-Jen Shih et al.', date='2025-10-08', venue='ICLR 2026', scope='TTS/LLM-rewritten ARC-E/C, SIQA, PIQA and GSM8K; LLaMA-Questions is a separate anchor.', metrics='Reasoning accuracy and post-question CoT delay on the accuracy/latency frontier.', access='Prompts and construction details in paper; released audio/evaluation package not located.', use='Reproduce the original reasoning/sufficiency setting.', caveat='Mostly single-turn synthetic speech; not a benchmark of multi-party interruption or first useful answer.', paper='https://arxiv.org/abs/2510.07497', artifact=None, result='Evaluates silent text reasoning in a streaming Moshi-family model.'),
    dict(id='2410.17196', name='VoiceBench', authors='Yiming Chen et al.', date='2024-10-22', venue='TACL 2026 (repository); initial preprint 2024', scope='Real and synthetic spoken instructions with speaker, environment and content variation.', metrics='Knowledge/QA accuracy, instruction following, safety and judged open answers.', access='Open repository + hlt-lab/voicebench dataset.', use='Language-competence and speech-robustness control.', caveat='Turn-based spoken instruction evaluation; does not directly evaluate continuous duplex reasoning.', paper='https://arxiv.org/abs/2410.17196', artifact='https://github.com/MatthewCYM/VoiceBench', result='Finds robustness gaps beyond clean-speech ASR or simple factual QA.'),
    dict(id='2508.13992', name='MMAU-Pro', authors='Sonal Kumar et al.', date='2025-08-19', venue='Preprint; primary source used to refresh original citation', scope='5,305 expert QA items; 49 skills across speech, sound, music and mixed audio.', metrics='Multiple-choice and open-answer audio reasoning by capability.', access='Public project, dataset and evaluation code.', use='Broader acoustic reasoning anchor from the original proposal.', caveat='Long-form, spatial and multi-audio understanding are different from real-time duplex control.', paper='https://arxiv.org/abs/2508.13992', artifact='https://sonalkum.github.io/mmau-pro/', result='Original evaluation finds substantial reasoning gaps even among its strongest tested models.'),
    dict(id='stepchat', name='StepAudioChat', authors='StepFun-Audio Team', date='2026-09-12', venue='Described in StepAudio 3 technical report', scope='Eight dialogue capability dimensions, including reasoning, memory, pragmatics and role.', metrics='Dimension and macro scores under the report’s judging protocol.', access='Benchmark described; public item/scoring release not located.', use='Contemporary dialogue/reasoning taxonomy.', caveat='An unreleased suite cannot yet support an independently reproduced comparison.', paper='https://arxiv.org/abs/2609.14005', artifact=None, result='Measures conversational intelligence alongside duplex and tool-use suites.'),
    dict(id='voilabench', name='Voila Benchmark', authors='Yemin Shi et al.', date='2025-05-05', venue='Described in Voila preprint', scope='Spoken versions of MMLU, MATH, HumanEval, NQ-Open and GSM8K.', metrics='Spoken knowledge / reasoning response correctness.', access='maitrix-org/Voila-Benchmark dataset released.', use='Additional spoken reasoning control for the Voila family.', caveat='Turn-wise synthetic evaluation; no direct concurrent-listening or correction metric.', paper='https://arxiv.org/abs/2505.02707', artifact='https://huggingface.co/datasets/maitrix-org/Voila-Benchmark', result='Allows reuse of a released spoken reasoning evaluation source.'),
]

DATASETS = [
    dict(name='SmoothConv', scale='100.53 h · Chinese', kind='Natural, multi-party, multi-channel', annotation='Expert transcripts; speaker IDs; complete / incomplete / backchannel / wait; timing and paralinguistic labels.', access='HF release · CC BY-NC 4.0', use='Small, high-quality control/speaker supervision; shares source conversations with DuplexConv.', source='https://huggingface.co/datasets/qualialabsAI/SmoothConv'),
    dict(name='DuplexConv', scale='2,000.21 h · Chinese', kind='Natural, multi-party, multi-channel', annotation='LLM-assisted transcripts, per-track VAD, turn state, speaker segments and acoustic/scene labels.', access='HF release · CC BY-NC 4.0', use='Larger conversational pretraining source; audit machine labels and split shared source sessions.', source='https://huggingface.co/datasets/OpenT2S/DuplexConv'),
    dict(name='otoSpeech conversational', scale='280 h raw / 141 h curated · English', kind='Natural, two-speaker channel-separated audio', annotation='Session/speaker metadata, redaction intervals and surveys; curated audio at 44.1 kHz.', access='Gated HF files; contact-sharing acceptance · CC BY 4.0', use='Wideband conversational acoustics; the 141 h subset is derived from the 280 h corpus, not extra hours.', source='https://huggingface.co/datasets/otoearth/otoSpeech-full-duplex-processed-141h'),
    dict(name='otoSpeech Task', scale='20.006 h · 58 sessions · English', kind='Natural task-oriented two-speaker conversation', annotation='48 kHz speaker channels; seven task types; synchronized events, stimuli and participant artifacts.', access='Gated HF files; contact-sharing acceptance · CC BY 4.0', use='Task-grounded state and evidence tracking; task outcomes need separate validation as reasoning labels.', source='https://huggingface.co/datasets/otoearth/otoSpeech-full-duplex-task-oriented-20h'),
    dict(name='Open Yap 1K', scale='1,000 h · 1,602 conversations · English', kind='Natural, familiar-speaker dyads; channel-separated 48 kHz audio', annotation='Word-level transcripts; speaker/device metadata; overlap and turn-gap statistics.', access='HF preview; full corpus by request under its Data Use Agreement', use='Natural timing and backchannels; a public sample does not make the full corpus an ungated download.', source='https://github.com/The-Agentic-Data-Co/open-yap-1k'),
    dict(name='Dual-track conversational TTS corpora', scale='5 h English + 10 h Chinese', kind='Natural paired recordings in isolated rooms', annotation='Separate clean tracks; transcripts; overlaps, backchannels, laughter and nonverbal vocalizations.', access='MagicHub releases; site-specific download terms', use='Small conversational-synthesis and channel/timing pilot; clean capture differs from noisy deployment.', source='https://arxiv.org/abs/2509.04093'),
    dict(name='Fisher English', scale='Approximately 1,960 h total · English', kind='Natural telephone dyads; 8 kHz, two channels', annotation='Conversation transcripts are separate LDC text packages; speaker metadata.', access='Licensed LDC speech + transcript packages', use='Established duplex timing / conversational modeling data; telephone bandwidth and acquisition costs matter.', source='https://catalog.ldc.upenn.edu/LDC2004S13', extra='https://catalog.ldc.upenn.edu/LDC2005S13'),
    dict(name='Switchboard-1 Release 2', scale='Approximately 260 h · English', kind='Natural topic-prompted telephone dyads; separate 8 kHz channels', annotation='Speaker information, corrected orthographic transcripts and available word alignments.', access='LDC97S62 · licensed', use='Turn-taking/disfluency baseline; small, narrowband and topic-prompted.', source='https://catalog.ldc.upenn.edu/LDC97S62'),
    dict(name='AMI Meeting Corpus', scale='Approximately 100 h · English', kind='Multi-party meetings with multiple microphones and video', annotation='Speaker/time-aligned transcripts; meeting structure and other annotations.', access='Corpus site; CC BY 4.0 for corpus audio/video (check annotation terms)', use='Speaker-specific state, overlap and longer context; scenario meetings differ from free-form assistants.', source='https://groups.inf.ed.ac.uk/ami/corpus/'),
    dict(name='SpokenWOZ', scale='249 h · 5.7K dialogues · 8 domains', kind='Human spoken task-oriented dialogue', annotation='Speech/text, dialogue state and task annotations; 203K turns.', access='Paper/project data release', use='Grounded slot/state tracking; turn-structured task data require a duplex timing construction.', source='https://arxiv.org/abs/2305.13040'),
    dict(name='DuplexChat', scale='282,634 h English + 132,723 h Japanese (manifest)', kind='Podcast-mined two-speaker spans; diarization/separation pipeline', annotation='Source URLs, span timestamps and speaker labels; reconstruct separate speaker tracks.', access='Manifests + reconstruction pipeline; audio not distributed. Manifest MIT; audio retains source rights.', use='Large-scale weak conversational pretraining. Reconstruction quality and source-audio access determine usable volume.', source='https://huggingface.co/datasets/sarulab-speech/DuplexChat', extra='https://arxiv.org/abs/2607.04941'),
    dict(name='HumDial Track 2 training split', scale='Over 107 h · English + Chinese · over 100 speakers', kind='Real human recordings for interruption/rejection scenarios', annotation='Eight interaction scenarios, including pauses, dissatisfaction, backchannels and third-party speech.', access='Official challenge data links and split rules', use='Controller supervision and real-recording validation; keep dev/test out of training.', source='https://github.com/ASLP-lab/Hum-Dial'),
    dict(name='DuplexOmni-Data', scale='Full reconstructed training set described as about 9 TB', kind='Generated duplex supervision and reproducible metadata', annotation='Duplex session metadata, data-generation pipeline and one completed parquet training shard.', access='Metadata + one shard released; full generated audio/data not bundled', use='A useful open synthesis recipe; reported full size is not the amount directly downloadable.', source='https://huggingface.co/datasets/MuyeHuang/DuplexOmni-Data', extra='https://github.com/MuyeHuang/DuplexOmni'),
]

RECIPES = [
    ('Moshi / PersonaPlex', 'Text/speech pretraining plus real and TTS-generated two-channel dialogues; PersonaPlex adds paired role/voice prompts.', 'Released models and inference; Moshi has a fine-tuning package. Full final dialogue mixtures not located.', 'https://arxiv.org/abs/2410.00037', 'https://arxiv.org/abs/2602.06053'),
    ('Think while listening', '1.8M Spoken CoT-Collection examples; text reasoning traces, rewritten spoken questions/answers, streaming alignment; correctness/length preference pairs.', 'Paper gives prompts and preparation details. No released CoT speech corpus or trained reasoning checkpoint located.', 'https://proceedings.iclr.cc/paper_files/paper/2026/file/75c45fca2aa416ada062b26cc4fb7641-Paper-Conference.pdf', None),
    ('BayLing-Duplex', '400K synthesized duplex SFT examples; follow-up DPO emphasizes response/interrupt timing.', 'Weights and inference released; full synthesized training set not located.', 'https://arxiv.org/abs/2606.14528', None),
    ('StepAudio 3 / MiniCPM-o 4.5', 'Large-scale multimodal foundation data, temporal interaction supervision and staged post-training; Step adds specialized teachers/merging.', 'Methods documented; complete real-time training mixtures not located.', 'https://arxiv.org/abs/2609.14005', 'https://arxiv.org/abs/2604.27393'),
    ('CharDuplex / FDGym', 'Character-conditioned generation/verification, TTS and forced alignment; about 756 h additional character speech; adaptive user rollouts for GRPO.', 'Recipe reported in September 28 preprint; artifacts not located. Character supervision is not a reasoning-revision dataset.', 'https://arxiv.org/abs/2609.34461', None),
]

THEMES = [
    'Time representation, speech decoding and reasoning location are separate design decisions: a decoder-only LLM can support either serialized or parallel duplex streams.',
    'Keeping acoustic generation away from text reasoning is a recurring strategy, implemented by separate speech decoders, hierarchy, frozen backbones or external reasoning models.',
    'Conversation timing, language competence, grounded tool execution and multi-party addressing require different evaluation conditions.',
    'Weights and inference code are much more common than fully reproducible training mixtures. Manifest, sample and gated releases need explicit labels.',
]
GAPS = [
    dict(id='g1', statement='Speaker-conditioned revision under late evidence: determine whose correction should update which hypothesis while preserving timing.', evidence='Think while listening addresses early CoT/DPO; FDB v1.5 and Duplex-MPE address overlap/addressing. These reviewed sources do not jointly establish causal speaker-specific reasoning revisions.', refs=['2510.07497','2507.23159','2609.31948']),
    dict(id='g2', statement='Measure useful answer timing alongside correctness and commitment errors rather than rewarding a fast filler or an early wrong answer.', evidence='SRQA measures reasoning delay; FDB v3 separates first response, tool and completion latency; τ-Voice measures task success and voice interaction. Their metrics are complementary.', refs=['2510.07497','2604.04847','2603.13686']),
    dict(id='g3', statement='Invalidate stale backend work when a correction arrives after delegation and before result admission.', evidence='Realtime-Venus, NVIDIA frontend–backend and Context Spanning provide different delegation/injection mechanisms. Robust correction during this interval needs an explicit controlled test.', refs=['2609.13814','2609.19334','2609.33443']),
    dict(id='g4', statement='Construct natural-acoustic prefix supervision with stable session/speaker splits and auditable sufficiency/revision labels.', evidence='SmoothConv/DuplexConv and otoSpeech preserve channels or timing; SRQA/CoT construction uses synthetic speech. Existing corpus labels are not automatically reasoning-sufficiency ground truth.', refs=['2510.07497']),
]

NARRATIVE = {
    'summary': [
        'The literature supports several concrete paths beyond the original Moshi-based study. For a text reasoning backbone, MiniCPM-o 4.5 exposes a streaming encoder and lightweight speech decoder, while BayLing-Duplex expresses dialogue control in a standard autoregressive vocabulary. Lychee-FD retains native parallel modeling but separates deeper semantic, acoustic and control parameters. Realtime-Venus and DuplexOmni make asynchronous backend reasoning an explicit system component.',
        'Moshi already has an LLM backbone. The architectural comparison is therefore about how time, concurrent streams and speech generation are represented, rather than whether a model uses an LLM. In particular, a text-only output vocabulary can coexist with continuous audio input and a separate speech decoder; “codec-free” usually describes the LLM interface, not necessarily the complete synthesizer.',
        'The March proposal already cites Think while listening, now an ICLR 2026 paper. It directly studies early CoT and semantic sufficiency, while its DPO stage also addresses adaptive reasoning. The strongest remaining question in the reviewed evidence is how a model revises a hypothesis when a delayed constraint arrives from the relevant speaker amid overlap, or while a delegated job is still running. This is a synthesis of the reviewed sources, not a claim of exhaustive novelty.',
        'Evaluation now extends well beyond single-turn spoken reasoning: τ-Voice measures grounded customer-service outcomes, FDB v2/v3 test corrections and tool use, and September’s Duplex-MPE directly targets multi-party addressing and silence. These suites complement VoiceBench and MMAU-Pro; a high score on one does not imply strong performance on another.',
    ],
    'scope': 'Review cutoff: 30 September 2026. Coverage prioritizes full-duplex architectural diversity and reproducible artifacts from 2024–2026, with older conversation corpora where they remain useful. Only the Literature review collection is present; project experiments and a new implementation proposal are outside this page.',
    'proposal_context': 'The supplied March 16 proposal connects a streaming encoder to a reasoning module and studies semantic sufficiency, hypothesis revision, and speaker/stream-aware policies. Its central outcome is a correct first useful response with appropriate conversational timing. This review refreshes the cited work and identifies existing components that could support those questions.',
    'architecture_lead': 'Table 1 separates the time/stream representation from the speech decoder and interaction policy. These are descriptive design families, not mutually exclusive rankings. Model sizes distinguish backbone parameters from total system parameters where the sources provide both.',
    'availability_lead': 'Table 2 audits releases separately from paper verification. “Not located” records the search outcome at the cutoff; it is not proof that no artifact exists. A demo, a family repository, or a reported release is weaker evidence than a model-specific checkpoint and runnable training package.',
    'benchmarks_lead': 'Table 3 distinguishes conversational timing, multi-turn state, tool/task completion and broad audio reasoning. FD-Bench and Full-Duplex-Bench are independent projects. FDB versions also change the test setting; their scores should not be combined into one leaderboard.',
    'data_lead': 'Table 4 compares natural conversation, task dialogue and reconstructed/generated sources. Corpus hours describe the reported collection, not the number of usable reasoning-supervision hours. Table 5 separately records model training recipes whose complete final mixtures are not necessarily downloadable.',
    'evaluation_note': 'For a comparison, pin the model and harness revision, prompt, task split, judge, audio condition, playback/clock behavior and backend latency. Report response initiation, correct useful answer, tool request, task completion and interruption stop time separately. Include correctness and false commitments at each timing point, and distinguish natural recordings from TTS-generated speech.',
    'access_note': 'SmoothConv and DuplexConv share underlying conversational sources: split by source session before using one for training and the other for evaluation. The otoSpeech curated corpus is a subset of the raw release. DuplexChat’s manifest license does not grant rights to the source podcast audio. These distinctions change what a reproducible training setup can claim.',
    'reading': [
        ('MiniCPM-o 4.5 → BayLing-Duplex', 'Compare a text backbone with a small speech decoder against a single vocabulary for speech and interaction control.', ['2604.27393','2606.14528']),
        ('Lychee-FD → Moshi / Think while listening', 'Inspect semantic/acoustic gradient separation, then identify which reasoning and control streams can be revised.', ['2607.06540','2410.00037','2510.07497']),
        ('Realtime-Venus → NVIDIA frontend–backend → Context Spanning', 'Compare foreground continuity, delegation signals and backend result admission; identify whether mid-tool interruption is supported.', ['2609.13814','2609.19334','2609.33443']),
        ('τ-Voice → FDB v3 → Duplex-MPE', 'Connect grounded task outcomes and corrections to multi-party addressability, silence and floor release.', ['2603.13686','2604.04847','2609.31948']),
    ],
    'methodology': 'Search angles covered native multi-stream models, serialized LLM decoders, codec-free text backbones, asynchronous delegation, reasoning under partial speech, interaction benchmarks, and natural/synthetic conversational data. Paper existence was verified through arXiv or publisher/venue pages; substantive descriptions use primary manuscripts. Availability was checked against official repositories and model/dataset cards. Repository release notes and cards can change after this date. No training, benchmarks, model downloads or provider calls were run.',
    'limitations': 'This is a focused architecture and resource review, not an exhaustive survey or an independently reproduced leaderboard. Some newly posted papers have no located release; some code packages expose inference or fine-tuning rather than foundation training. Unknown authors/venues and artifact status remain explicit. Closed realtime APIs appear as comparators in benchmark papers, but their private internal architecture cannot be inferred from those results.',
}
