#!/usr/bin/env python3
"""Generate shared PDF/SVG benchmark plots, exact-value TeX tables and provenance.

Usage: python scripts/build_performance.py [--results JSON]
Plots never impute missing results, normalize to a model, or combine protocols.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "research"))
sys.path.insert(0, str(ROOT / "scripts"))
from performance_profiles import PROFILES, SHORT_NAMES
from generate import tex

COLORS = ["#2469a0", "#d46a22", "#75818b", "#238875", "#925ab0", "#a94f69", "#8b7939"]

def all_groups(data):
    return data["groups"] + data.get("supplementary_groups", []) + data.get("additional_system_groups", [])

def display_rows(group):
    return [row for row in group["rows"] if row["role"] != "text_control"]

def metrics(data, group):
    if group["id"] == "tau_aa":
        return data["domain_metric_labels"] + group["metric_labels"]
    return group["metric_labels"]

def scores(group, row):
    if group["id"] == "tau_aa":
        return row["domain_scores"] + row["source_values"]
    return [None if value is None else value * definition.get("scale", row["scale"]) for value, definition in zip(row["source_values"], group.get("metric_specs", [{}] * len(row["source_values"])))]

def specs(data, group):
    return group.get("metric_specs", [{"unit": "%", "higher": True, "decimals": display_rows(group)[0]["decimals"]} for _ in metrics(data, group)])

def exact_table(data, group):
    labels = metrics(data, group)
    definitions = specs(data, group)
    rows = display_rows(group)
    best = []
    for index, definition in enumerate(definitions):
        vals = [scores(group, row)[index] for row in rows if scores(group, row)[index] is not None]
        best.append((max if definition["higher"] else min)(vals))
    cites = list(dict.fromkeys(data["sources"][key]["cite"] for key in group["source_ids"]))
    unit_note = "Each column states its unit and direction. " if "metric_specs" in group else "Percent; higher is better. "
    columns = r">{\raggedright\arraybackslash}p{0.32\tablewidth}" + "".join(r">{\centering\arraybackslash}p{" + f"{0.68/len(labels):.6f}" + r"\tablewidth}" for _ in labels)
    lines = ["% Generated by scripts/build_performance.py; edit research/reported-performance.json.", r"\begin{table}[H]", r"\centering\small", r"\setlength{\tabcolsep}{3pt}", r"\setlength{\tablewidth}{\dimexpr\linewidth-" + str(2*len(labels)) + r"\tabcolsep\relax}", r"\renewcommand{\arraystretch}{1.06}", r"\caption{" + tex(group["benchmark"] + ". " + unit_note + "Bold: best among the displayed references, not a source-wide or current SoTA.") + r" \citep{" + ",".join(cites) + "}}", r"\label{tab:performance-" + group["id"] + "}", r"\begin{tabular}{@{}" + columns + "@{}}", r"\toprule"]
    aliases = {"OpenbookQA": "OBQA", "TriviaQA": "TriQA", "Conditional answer": "Answer accuracy", "Answering-window yield": "Yield", "DuplexBench ToR": "DB v1.5 ToR"}
    headings = ["Model / configuration"] + [aliases.get(label, label) + (" (" + definition["unit"] + "; " + ("higher" if definition["higher"] else "lower") + ")" if "metric_specs" in group else "") for label, definition in zip(labels, definitions)]
    lines += [" & ".join(r"\textbf{" + tex(heading) + "}" for heading in headings) + r" \\", r"\midrule"]
    for row in rows:
        name = tex(row["model"])
        if row["role"] == "selected": name = r"\textbf{" + name + "}"
        cells = [name]
        for value, definition, winner in zip(scores(group, row), definitions, best):
            rendered = "NR" if value is None else f"{value:.{definition['decimals']}f}"
            if value is not None and abs(value - winner) < 1e-9: rendered = r"\textbf{" + rendered + "}"
            cells.append(rendered)
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"

def radar(ax, labels, rows, values, title):
    import numpy as np
    angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)
    closed = np.r_[angles, angles[0]]
    ax.set_theta_offset(np.pi/2)
    ax.set_theta_direction(-1)
    ax.set_ylim(0, 100)
    ax.set_yticks([20, 40, 60, 80, 100])
    ax.set_yticklabels(["20", "40", "60", "80", "100"], fontsize=8, color="#687580")
    ax.set_rlabel_position(15)
    ax.set_xticks(angles)
    ax.set_xticklabels(labels, fontsize=10)
    ax.tick_params(axis="x", pad=12)
    ax.grid(color="#d6dfe5", linewidth=0.7)
    ax.spines["polar"].set_color("#b6c1c9")
    ax.set_title(title, fontsize=12, fontweight="bold", pad=29)
    for index, (row, vals) in enumerate(zip(rows, values)):
        assert len(vals) == len(labels) and all(value is not None for value in vals)
        color = COLORS[index % len(COLORS)]
        style = "-" if row["role"] == "selected" else "--"
        ax.plot(closed, vals + [vals[0]], linewidth=2, marker="o", markersize=3.2, linestyle=style, color=color, label=SHORT_NAMES.get(row["model"], row["model"]))
        if row["role"] == "selected": ax.fill(closed, vals + [vals[0]], color=color, alpha=0.045)

def bars(ax, labels, vals, colors, title, limit, decimals=1, show_labels=True):
    import numpy as np
    positions = np.arange(len(vals))
    present = [index for index, value in enumerate(vals) if value is not None]
    ax.barh(positions[present], [vals[index] for index in present], color=[colors[index] for index in present], height=0.56)
    ax.set_yticks(positions)
    if show_labels: ax.set_yticklabels(labels, fontsize=10)
    else: ax.tick_params(axis="y", labelleft=False)
    ax.set_ylim(len(vals)-0.5, -0.5)
    ax.set_xlim(0, limit)
    ax.set_title(title, fontsize=10, pad=15, fontweight="bold")
    ax.grid(axis="x", color="#dce3e8", linewidth=0.7)
    ax.set_axisbelow(True)
    for edge in ("top", "right", "left"): ax.spines[edge].set_visible(False)
    ax.spines["bottom"].set_color("#c0c9d0")
    ax.tick_params(length=0)
    for pos, value in zip(positions, vals):
        ax.text(limit*0.025 if value is None else value + limit*0.025, pos, "NR" if value is None else f"{value:.{decimals}f}", ha="left", va="center", fontsize=9, color="#6e7780" if value is None else "#26343e")

def plot_profile(data, group, profile, plt):
    rows = display_rows(group)
    kind = profile["kind"]
    if kind == "radar":
        rows = [next(row for row in rows if row["model"] == name) for name in profile["models"]]
        fig = plt.figure(figsize=(8.4, 4.8))
        ax = fig.add_axes([0.20, 0.20, 0.60, 0.60], projection="polar")
        radar(ax, profile["axes"], rows, [scores(group, row) for row in rows], profile["title"])
        fig.legend(*ax.get_legend_handles_labels(), loc="lower center", bbox_to_anchor=(0.5, 0.00), ncol=2, frameon=False, fontsize=10)
    elif kind == "paired-radar":
        fig = plt.figure(figsize=(9.0, 4.7))
        for index, condition in enumerate(("explicit", "implicit")):
            ax = fig.add_axes([0.07 + index*0.50, 0.24, 0.36, 0.62], projection="polar")
            selected = [next(row for row in rows if row["model"].startswith(name) and condition in row["model"]) for name in ("MiniCPM", "Moshi", "Voila")]
            clean_rows = [{**row, "model": row["model"].split(" (")[0]} for row in selected]
            radar(ax, profile["axes"], clean_rows, [scores(group, row) for row in selected], condition.capitalize() + " addressing")
        fig.legend(*ax.get_legend_handles_labels(), loc="lower center", bbox_to_anchor=(0.5, 0.02), ncol=3, frameon=False, fontsize=10)
    elif kind == "domain-radar":
        fig = plt.figure(figsize=(9.2, 4.8))
        ax = fig.add_axes([0.05, 0.24, 0.38, 0.61], projection="polar")
        radar(ax, profile["axes"], rows, [row["domain_scores"] for row in rows], "Domain task success (%)")
        right = fig.add_axes([0.73, 0.28, 0.24, 0.51])
        bars(right, [SHORT_NAMES.get(row["model"], row["model"]) for row in rows], [row["source_values"][0] for row in rows], COLORS[:len(rows)], "Reported macro (%) ↑", 100)
        fig.legend(*ax.get_legend_handles_labels(), loc="lower center", bbox_to_anchor=(0.5, 0.01), ncol=2, frameon=False, fontsize=9)
    else:
        rows = [row for row in rows if row["role"] != "backend_only"]
        labels = metrics(data, group)
        definitions = specs(data, group)
        names = [SHORT_NAMES.get(row["model"], row["model"]) for row in rows]
        titles = labels
        if group["id"] == "flair_interaction": titles = ["Turn-taking TOR", "Turn delay", "Barge-in TOR", "GPT-4o quality", "Barge-in delay"]
        if group["id"] == "duplexomni": titles = ["DuplexBench\nToR (v1.5)", "Big Bench\nAudio", "Daily-Omni\n(streaming)", "LibriSpeech\nWER", "Response\nlatency"]
        fig, axes = plt.subplots(1, len(labels), figsize=(11.0, 4.0) if group["id"] == "duplexomni" else (9.4, 3.1), sharey=True, squeeze=False)
        for index, ax in enumerate(axes[0]):
            definition = definitions[index]
            vals = [scores(group, row)[index] for row in rows]
            maximum = max(value for value in vals if value is not None)
            limit = (maximum*1.35 if "WER" in titles[index] else 115) if definition["unit"] == "%" else (5.9 if definition["unit"] == "0–5" else maximum*1.30)
            direction = "↑" if definition["higher"] else "↓"
            bars(ax, names, vals, COLORS[:len(rows)], titles[index] + "\n(" + definition["unit"] + ") " + direction, limit, definition["decimals"], index == 0)
        fig.subplots_adjust(left=0.25, right=0.98, bottom=0.20, top=0.77, wspace=0.35)
    return fig

def coverage_plot(data, plt):
    import numpy as np
    from matplotlib.colors import ListedColormap
    columns = [("srqa", "SRQA"), ("tau_original", "τ-Voice\noriginal"), ("tau_aa", "τ-Voice\nAA"), ("fdb3", "FDB-v3"), ("echo", "EchoChain"), ("mpe", "Duplex-MPE")]
    names = [row["system"] for row in data["coverage"]]
    def reported(row, ident):
        if ident == "tau_original": return row["tauvoice"] == "original_protocol"
        if ident == "tau_aa": return row["tauvoice"] == "aa_variant_only"
        key = "echochain" if ident == "echo" else ident
        return row[key] in {"reported", "study_configs", "reported_both_frontends"}
    cells = np.array([[int(reported(row, ident)) for ident, _ in columns] for row in data["coverage"]])
    fig, ax = plt.subplots(figsize=(9.0, 2.0 + 0.28*len(names)))
    ax.imshow(cells, cmap=ListedColormap(["#f0f2f4", "#d2e8dc"]), vmin=0, vmax=1, aspect="auto")
    ax.set_xticks(range(len(columns)), [label for _, label in columns], fontsize=10)
    ax.set_yticks(range(len(names)), names, fontsize=10)
    ax.tick_params(length=0)
    for y in range(len(names)):
        for x in range(len(columns)):
            ax.text(x, y, "Reported" if cells[y, x] else "NR", ha="center", va="center", fontsize=10, color="#214d38" if cells[y, x] else "#6e7780")
    for edge in ax.spines.values(): edge.set_visible(False)
    fig.subplots_adjust(left=0.25, right=0.98, top=0.89, bottom=0.20)
    return fig

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=ROOT / "research" / "reported-performance.json")
    args = parser.parse_args()
    data = json.loads(args.results.read_text())
    audit = json.loads((ROOT / "research" / "reported-performance-audit.json").read_text())
    digest = hashlib.sha256(args.results.read_bytes()).hexdigest()
    assert audit["status"] == "passed" and audit["data_sha256"] == digest, "Re-audit the current source data before plotting."
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10, "svg.fonttype": "none", "svg.hashsalt": "ai2ai-duplex-performance", "figure.facecolor": "white", "axes.facecolor": "white", "text.color": "#26343e", "axes.labelcolor": "#26343e", "xtick.color": "#596772", "ytick.color": "#596772", "pdf.fonttype": 42})
    output = ROOT / "figures" / "performance"
    output.mkdir(parents=True, exist_ok=True)
    groups = {group["id"]: group for group in all_groups(data)}
    records = []
    def save(fig, ident):
        artifacts = {}
        for extension in ("pdf", "svg", "png"):
            path = output / (ident + "." + extension)
            fig.savefig(path, dpi=170, facecolor="white", bbox_inches="tight", pad_inches=0.16)
            if extension == "svg":
                path.write_text("\n".join(line.rstrip() for line in path.read_text().splitlines()) + "\n")
            artifacts[extension] = {"file": str(path.relative_to(ROOT)), "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
        plt.close(fig)
        return artifacts
    coverage = save(coverage_plot(data, plt), "coverage")
    for profile in PROFILES:
        group = groups[profile["group"]]
        (ROOT / "tables" / ("performance-" + group["id"] + ".tex")).write_text(exact_table(data, group))
        artifacts = save(plot_profile(data, group, profile, plt), profile["id"])
        records.append({**profile, "sources": [data["sources"][key] for key in group["source_ids"]], "table": "tables/performance-" + group["id"] + ".tex", "artifacts": artifacts, "table_rows": [{"model": row["model"], "scores": scores(group, row)} for row in display_rows(group)]})
    payload = {"revision_date": data["revision_date"], "evidence_cutoff": data["evidence_cutoff"], "data_sha256": digest, "convention": "Radars use raw 0–100 percentages. No polygon-area ranking, normalization to a reference, imputation or cross-protocol averaging. Mixed units and fewer than three metrics use separate bar axes. No error bars: these are source-reported point estimates, not independent reruns.", "coverage": coverage, "profiles": records}
    (ROOT / "research" / "performance-plots.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    sections = ROOT / "sections"
    sections.mkdir(exist_ok=True)
    lines = ["% Generated by scripts/build_performance.py; edit the structured sources.", r"\subsection{What is reported, and what is missing}", "The seven selected systems have sparse coverage across the selected benchmark families (Figure~\\ref{fig:performance-coverage}). Missing results are NR, not zero. FLAIR's and DuplexOmni's study-specific suites do not fill an FDB-v3 or SRQA cell; VoiceChat does report FDB-v3. Source versions, table/page locators and PDF hashes are archived alongside the reported values; these checks verify transcription, not experimental reproduction.", r"\begin{figure}[H]", r"\centering", r"\includegraphics[width=\linewidth]{figures/performance/coverage.pdf}", r"\caption{Reported selected-system coverage in the five benchmark families, with the two $\tau$-Voice implementations kept separate. NR means no matching result was located in the reviewed sources.}", r"\label{fig:performance-coverage}", r"\end{figure}", r"\paragraph{How to read the profiles.}", "Radars show raw percentages on a shared 0--100 scale within one protocol; their area is not a model score. Separate bars are used for mixed units or fewer than three metrics. Solid lines denote selected configurations; dashed lines denote reference/ablation configurations. Compare named curves and individual metrics, not polygon area or panels from different benchmarks. No missing cell is imputed and no cross-benchmark average is calculated. The figures use source-reported point estimates, without reproducing experiments or inventing uncertainty bars.", "Closed references are benchmark-source leaders where reported, not current global SoTA. SRQA and Duplex-MPE do not test a closed voice system. FLAIR's historical interaction table contains only one closed API reference, with no precise revision. Imported reference scores and later system-report evaluations are not a common rerun."]
    for record in records:
        cites = list(dict.fromkeys(source["cite"] for source in record["sources"]))
        width = r"0.78\linewidth" if record["kind"] == "radar" else r"\linewidth"
        lines += [r"\clearpage", r"\subsection{" + tex(record["title"]) + "}", tex(record["note"]) + r" \citep{" + ",".join(cites) + "}", r"\begin{figure}[H]", r"\centering", r"\includegraphics[width=" + width + "]{" + record["artifacts"]["pdf"]["file"] + "}", r"\caption{" + tex(record["title"] + ". " + ("Raw percentages; higher is better. " if record["kind"] != "facets" else "Units and directions are labeled per panel. ") + "Exact values and additional context references are in the adjacent table.") + "}", r"\label{fig:performance-" + record["id"] + "}", r"\end{figure}", r"\input{" + record["table"].removesuffix(".tex") + "}", r"{\small\textbf{Reading this profile (review interpretation).} " + tex(record["takeaway"]) + "}"]
    lines += [r"\paragraph{Text controls, not voice competitors.}"]
    for control in data["text_controls"]:
        rendered = " / ".join(f"{value*control['scale']:.{control['decimals']}f}" for value in control["source_values"])
        description = control["model"] + ": " + rendered + "% (" + " / ".join(control["metric_labels"]) + "). " + control["notes"]
        lines.append(tex(description) + r" \citep{" + data["sources"][control["source"]]["cite"] + "}\\par")
    (sections / "performance.tex").write_text("\n".join(lines) + "\n")
    print(f"Generated {len(records)+1} shared PDF/SVG plots, {len(records)} exact-value TeX tables and plot provenance.")

if __name__ == "__main__":
    main()
