#!/usr/bin/env python3
"""Generate short tables and linked references from archived primary facts."""
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "research"))
from brief_data import TABLES, QUESTIONS, FIGURES, TIMING_POINTS
import focused_review
from generate import tex, write

def table(path, label, caption, heads, widths, rows):
    gaps = 2 * (len(heads) - 1)
    columns = "".join(f">{{\\raggedright\\arraybackslash}}p{{{width:.2f}\\tablewidth}}" for width in widths)
    lines = ["% Generated by scripts/generate_brief.py; edit research/brief_data.py.", r"\begin{table}[H]", r"\centering\small", r"\setlength{\tabcolsep}{4pt}", r"\setlength{\tablewidth}{\dimexpr\linewidth-" + str(gaps) + r"\tabcolsep\relax}", r"\renewcommand{\arraystretch}{1.06}", r"\caption{" + tex(caption) + "}", r"\label{" + label + "}", r"\begin{tabular}{@{}" + columns + "@{}}", r"\toprule", " & ".join(r"\textbf{" + tex(h) + "}" for h in heads) + r" \\", r"\midrule"]
    for index, cells in enumerate(rows):
        lines.append(" & ".join(cells) + r" \\")
        if index < len(rows) - 1:
            lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(path, "\n".join(lines))

def main():
    for entry in TABLES:
        assert len(entry["rows"]) == 5
        cells = []
        for name, key, *rest in entry["rows"]:
            first = r"\textbf{" + tex(name) + "}"
            if entry["id"] != "systems":
                first += r" \citep{" + key + "}"
            cells.append([first] + [tex(value) for value in rest])
        table(ROOT / "tables" / ("brief-" + entry["id"] + ".tex"), entry["label"], entry["caption"], entry["headers"], entry["widths"], cells)
    rows = [[r"\textbf{" + tex(title) + r"}\par " + tex(question), tex(test), tex(metric)] for title, question, test, metric in QUESTIONS]
    table(ROOT / "tables" / "brief-questions.tex", "tab:questions", "Five discussion questions: small falsifiable tests, not claimed results.", ["Question", "First paired test", "Measure"], [0.32, 0.43, 0.25], rows)
    digest = json.loads((ROOT / "research" / "literature.json").read_text())
    keys = {key for entry in TABLES for _, key, *_ in entry["rows"]}
    keys.update(key for figure in FIGURES for key in figure["paper_keys"])
    sources = {paper["key"]: paper for paper in digest["papers"]}
    lines = ["% Generated compact linked references; full BibTeX in references.bib.", r"\begin{thebibliography}{99}"]
    for key in focused_review.PAPERS:
        if key not in keys:
            continue
        paper = sources[key]
        author = paper["authors"][0].split(",")[0]
        author_label = author + (" et al." if len(paper["authors"]) > 1 else "")
        year = focused_review.VENUES[key][1] if key in focused_review.VENUES else paper["date"][:4]
        link = paper.get("publisher_source") or paper["source"]
        display_year = {"step3": "2026a", "fdb3": "2026b"}.get(key, year)
        lines += [r"\bibitem[" + tex(author_label) + "(" + display_year + ")]" + "{" + key + "}", tex(author_label) + " (" + display_year + "). " + r"\href{" + link + "}{" + tex(paper["title"]) + "}. " + tex(paper["venue"]) + "."]
    for name, key, *_ in TABLES[-1]["rows"]:
        fullrow = next(row for row in focused_review.CATEGORIES[-1]["rows"] if row["cite"] == key)
        author = focused_review.DATA_AUTHORS[key]
        date_label = {"ototask": "n.d.-a", "otoconv": "n.d.-b"}.get(key, "n.d.")
        lines += [r"\bibitem[" + tex(author) + "(" + date_label + ")]{" + key + "}", tex(author) + " (" + date_label + "). " + r"\href{" + fullrow["links"][0][1] + "}{" + tex(name) + " dataset documentation}. Accessed 30 September 2026."]
    lines += [r"\end{thebibliography}"]
    write(ROOT / "brief-references.tex", "\n".join(lines))
    detailed_figures = [{"id": record["id"], "file": record["image"], "paper_keys": [record["id"]], "source_figures": [record["figure"]]} for record in json.loads((ROOT / "figures/papers/manifest.json").read_text())["sources"] if record["id"] in {"duplexomni", "voicechat"}]
    payload = {"revision_date": "2026-10-01", "literature_cutoff": focused_review.DATE, "format": "Five brief pages, including reported performance, plus availability/references; speech-research discussion", "figures": FIGURES, "detailed_only_figures": detailed_figures, "timing_parameters": TIMING_POINTS, "architecture_provenance": "figures/papers/manifest.json", "copyright_scope": "Seven attributed architecture screenshots in the detailed report; the meeting brief retains its original five. Crop margins/prose and select StepAudio panel B. Labels/arrows are not edited; rights remain with original holders. Conceptual trace and timing plot are original. Full papers/private proposal are not redistributed.", "omissions": "StepAudio Figure 7A (adaptive routing) omitted, explicitly labeled. Method details, losses and mixtures remain in detailed-report.pdf and original papers."}
    write(ROOT / "research" / "figure-sources.json", json.dumps(payload, ensure_ascii=False, indent=2))
    print("Generated four top-five compact tables, five RQ rows, compact linked references, and figure-source notes.")

if __name__ == "__main__":
    main()
