#!/usr/bin/env python3
"""Generate a compact benchmark-results table from source-checked reported data.

Usage: python scripts/make_table_reported_performance.py [--results JSON] [--output TEX]
This reports published numbers, never results of experiments run in this workspace.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from generate import tex
from generate_brief import table

def values(row):
    return " / ".join("n/a" if value is None else f"{value * row['scale']:.{row['decimals']}f}" for value in row["source_values"])

def model_cell(row):
    return r"\textbf{" + tex(row["model"]) + r"}\par " + tex(values(row))

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=ROOT / "research" / "reported-performance.json")
    parser.add_argument("--output", type=Path, default=ROOT / "tables" / "brief-performance.tex")
    args = parser.parse_args()
    data = json.loads(args.results.read_text())
    rows = []
    for group in data["groups"]:
        for row in group["rows"]:
            assert len(row["source_values"]) == len(group["metric_labels"])
            assert all(value is None or 0 <= value * row["scale"] <= 100 for value in row["source_values"])
            assert row["source"] in data["sources"]
        selected = [row for row in group["rows"] if row["role"] == "selected" and row.get("display", True)]
        closed = [row for row in group["rows"] if row["role"] == "closed_voice"]
        winners = [row for row in closed if row.get("best_closed")]
        for row in winners:
            assert all(value == max(other["source_values"][index] for other in closed) for index, value in enumerate(row["source_values"]))
        citations = list(dict.fromkeys(data["sources"][key]["cite"] for key in group["source_ids"]))
        benchmark = r"\textbf{" + tex(group["benchmark"]) + r"}\par " + tex(group["protocol"]) + r"\par\citep{" + ",".join(citations) + "}"
        selected_cell = r"\par\smallskip ".join(model_cell(row) for row in selected) if selected else "NR"
        closed_cell = r"\par\smallskip ".join(model_cell(row) for row in winners) if winners else "No closed voice result."
        rows.append([benchmark, selected_cell, closed_cell])
    caption = "Reported performance (percent, higher is better). Scores follow the metric order in each row; compare only within a protocol. NR: selected-system result not located, not zero. Closed references are the best in the stated source comparison, not a current global leaderboard."
    table(args.output, "tab:performance", caption, ["Benchmark / metric order", "Selected systems", "Best closed voice in source"], [0.28, 0.44, 0.28], rows)
    header = "% Generated by scripts/make_table_reported_performance.py; edit research/reported-performance.json."
    generated = args.output.read_text().splitlines()
    generated[0] = header
    args.output.write_text("\n".join(generated) + "\n")
    controls = data["text_controls"]
    tau = next(row for row in controls if row["benchmark"] == "tau_original")
    explicit = next(row for row in controls if row["benchmark"] == "mpe" and "explicit," in row["model"])
    implicit = next(row for row in controls if row["benchmark"] == "mpe" and "implicit," in row["model"])
    extra = [r"\smallskip", r"{\small\textbf{Text controls, not voice competitors.} " + tex("Original τ-Voice: GPT-5 reasoning, " + values(tau) + "% task pass@1. Duplex-MPE: Gemini 3.1 Pro with speaker-attributed transcripts, explicit " + values(explicit) + ", implicit " + values(implicit) + " (response presence / conditional answer / silence, %; Table 17 reference run). No fresh-onset or stopping score; not a speech-model upper bound.") + r" \citep{tauvoice,mpe}}"]
    args.output.write_text(args.output.read_text() + "\n" + "\n".join(extra) + "\n")
    dpo = next(row for group in data["groups"] if group["id"] == "srqa" for row in group["rows"] if "qc_threshold" in row)
    delays = " / ".join(f"{value:.1f}" for value in dpo["latency_tokens"])
    macros = [header, r"\newcommand{\srqaQCThreshold}{" + f"{dpo['qc_threshold']:.2f}" + "}", r"\newcommand{\srqaDPODelays}{" + delays + "}"]
    args.output.with_name("performance-macros.tex").write_text("\n".join(macros) + "\n")
    print("Generated a six-protocol reported-results table covering five benchmarks, with separate text controls.")

if __name__ == "__main__":
    main()
