"""Readable S2 single-request results, with real replay and explicit limits."""
from html import escape
import json
from pathlib import Path
from build_current_experiments import ROOT,table,version_assets
from site_navigation import project_tabs,experiment_subtabs


def section(title,body):return '<section class="section"><h2>'+title+'</h2>'+body+'</section>'
def paragraphs(*texts):return ''.join('<p>'+s+'</p>' for s in texts)
def labeled(number,headers,rows,caption):return '<div class="asset-block">'+table(headers,rows)+'<p class="cap"><span class="asset-label">Table '+str(number)+'.</span> '+caption+'</p></div>'


def main():
    study=json.loads((ROOT/'research/s2-single-study.json').read_text());first=study['initial_review']
    successful=next(c for c in study['conditions'] if c['id']=='S2-01b')
    q=first['runtime_qualification'];body=experiment_subtabs('s2')
    body+='<header class="hero"><p class="eyebrow">Single-request reasoning · 9 October 2026</p><h1>S1 can speak a response informed by S2.</h1><p class="lede">The harness has completed a real S1–S2 exchange on one human question. A separate arithmetic test exposed a reasoning-budget failure, which we investigated with direct provider controls.</p>'+paragraphs('S1 listens and speaks while the separate S2 backend reasons. In the successful human example, S2 returns a short answer about outlet stores, and S1 finishes its spoken explanation with matching information. The S2 call is explicitly forced in this example; the arithmetic follow-up also tests whether S1’s own THINK command can start the exchange.')+'</header>'
    audio_scope='Each selectable condition contains <b>one user request and no interruption</b>. The current selector compares the original DailyTalk human question with S2 dispatch off or explicitly forced. '
    if study['followup_review']:audio_scope+='It also includes the measured arithmetic conditions, using authored Flite synthetic speech. '
    else:audio_scope+='The synthetic arithmetic request and its pending follow-up are discussed below. '
    audio_scope+='Full replay keeps the original gaps: the left channel is the user, and the right is the model audio that reached playback.'
    body+=section('Listen to the actual experiment',paragraphs(audio_scope)+'<label for="s2-case">Condition <select id="s2-case"></select></label><h3 id="condition-title"></h3><p id="condition-source"></p><blockquote id="user-request"></blockquote><p id="condition-finding"></p><p><b>Full user/model replay</b></p><audio id="s2-conversation" controls preload="metadata"></audio><p><b>Model playback only</b></p><audio id="s2-model" controls preload="metadata"></audio><p><b>Independent transcript of played speech</b></p><blockquote id="played-transcript"></blockquote><p><b>S2’s complete final guidance</b></p><blockquote id="final-guidance"></blockquote><p id="s2-detail"></p>')
    body+=section('What the successful human example shows',paragraphs(
        'The user asks about the difference between an outlet and a regular store. S1 begins “An outlet…” while S2 works in the background. S2 finishes its request in about <b>1.54 seconds</b>, using <b>336 completion tokens</b>, and returns: <b>“Outlet stores sell discounted items; regular stores sell products at full price.”</b>',
        'The harness forwards that completed clause as plain text in the next S1 message’s <code>from_s2</code> field. At step 14, S1 receives the clause and generates “discounted”, followed by the rest of the discount/full-price explanation. The independent transcript of actual playback is <b>“An outlet is a store that sells discounted items, a regular store sells products at full price.”</b>',
        'During the S2 request, S1 processes three further audio packets and its speech overlaps the active S2 request for about <b>'+f"{successful['speech_overlap_with_s2_seconds']:.2f}"+' seconds</b>. This is measured software request/playback overlap, not a GPU-kernel trace. The complete clause waits about <b>0.196 seconds</b> before being delivered to S1.',
        'This establishes a working one-request reasoning handoff. It does not establish that S2 improves factual accuracy: the S1-only condition already gives a relevant outlet explanation. It also does not isolate the effect of guidance from the forced THINK cue. Both the intervention and the returned model fields remain recorded.'))
    rows=[(c['id'],c['label'],c['source'],c['finding']) for c in study['conditions']]
    body+=section('Current conditions',labeled(1,['ID','Condition','User audio','Observed result'],rows,'Conditions are separate replays of one request, not successive questions in a multi-turn conversation. Failed earlier arithmetic output is described below rather than presented as a successful current example.'))
    timing=[('S1 p95',f"{q['baseline']['p95_s1_seconds']:.3f} s",f"{q['with_s2_load']['p95_s1_seconds']:.3f} s"),('Talker p95',f"{q['baseline']['p95_talker_seconds']:.3f} s",f"{q['with_s2_load']['p95_talker_seconds']:.3f} s"),('Largest input queue delay',f"{q['baseline']['max_input_queue_delay_seconds']*1000:.3f} ms",f"{q['with_s2_load']['max_input_queue_delay_seconds']*1000:.3f} ms"),('Largest speech queue delay',f"{q['baseline']['max_speech_queue_delay_seconds']*1000:.2f} ms",f"{q['with_s2_load']['max_speech_queue_delay_seconds']*1000:.2f} ms")]
    body+=section('The GPU setup keeps reasoning from slowing speech',paragraphs('The full audio studies use <b>two H100 SXM GPUs with 80 GB each</b>. Thinker, Talker, MTP and Code2Wav share GPU 0, using the verified S1 setup. S2 has GPU 1 to itself. We first replay a known sky question with S2 idle, then with continuous S2 load. Both latency checks pass before the behavioral cases run. Table 2 shows that this measured layout has no material S1 or speech slowdown under S2 load.')+labeled(2,['Measurement','S2 idle','S2 under load'],timing,'Job 1036322; 36 measured requests per condition after four warmup steps. p95 is the 95th-percentile request time. The limit is 0.384 seconds for S1 and Talker, with additional queue and relative-slowdown checks. These measurements do not establish global hardware optimality.')+paragraphs('S2 stays loaded on its dedicated GPU even when dispatch is disabled, so the comparison keeps the same services and allocation. All GPU jobs run sequentially, with a maximum of two GPUs active. The provider-only diagnostic uses one H100 80 GB for S2 and loads no S1 or speech model. CPU transcript audits use zero GPUs.'))
    body+=section('Why the first arithmetic attempt did not answer',paragraphs(
        'The arithmetic recording says <b>“Please calculate seventeen times twenty-three.”</b> S1 transcribes it correctly as “Please calculate 17 times 23” and emits its own THINK command. In both initial conditions, the played speech is an acknowledgment: “Sure, let me work that out. Give me a sec to double check the numbers.” No result follows.',
        'In the S2-enabled attempt, the reasoning backend consumes all <b>2,048 allowed tokens</b> in about <b>9.27 seconds</b>. Its finish reason is <code>length</code>, its final-content channel is empty, and it queues no complete clause. As a result, there is no answer for the harness to deliver. S1 is still keeping up with input, so the trace does not support blaming this failure on GPU contention or missing audio.',
        'The THINK cue was already present in the model’s arithmetic response, so this failure is also distinct from the forced-history issue corrected for the outlet test. The earlier failed bread study similarly ran out of S2 tokens before closing its first guidance bracket. A low output allowance can stop this Thinking backend before it produces anything usable, even on a small arithmetic question.'))
    control_names={'captured_context_2048':'Original User/Agent context; 2,048-token limit',
        'captured_context_4096':'Original User/Agent context; 4,096-token limit',
        'user_only_4096':'Actual user question only; top_p = 1',
        'user_only_top_p_095_4096':'Actual user question only; top_p = 0.95'}
    controls=[(control_names[c['name']],c['max_tokens'],c['usage']['completion_tokens'],f"{c['wall_seconds']:.2f} s",'391; complete clause') for c in study['provider_controls']['cases']]
    body+=section('Direct provider controls narrow the problem',paragraphs('We replayed the captured arithmetic request directly through the same Thinking checkpoint on a separate one-H100 job. Table 3 compares the original dialogue wrapper, a larger output allowance, and a context containing only S1’s actual user transcription. All four controls return 391 in a completed guidance clause. The two user-only controls take about 1.3–1.5 seconds.')+labeled(3,['Provider input and sampling control','Token allowance','Tokens used','Request time','Final answer'],controls,'Provider job 1036482; temperature 0.6, top_k 20 and requested seed 17. The final user-only row uses top_p 0.95. No S1 model or spoken-answer path is loaded in this diagnostic.')+paragraphs('The two original-context runs did not share an identical private-generation prefix despite the same requested seed. We therefore cannot attribute the different lengths solely to the output allowance or promise deterministic replay from a seed. These controls show that the backend can solve the question and that the original failure is not a general inability to multiply 17 by 23. They do not yet prove that every full audio run will finish.'))
    if study['followup_review']:
        follow=study['followup_review'];items=[c for c in follow['cases'] if not c['is_calibration']]
        body+=section('The full arithmetic follow-up',paragraphs('Job <b>1036593</b> repeats the unchanged S1 input, prompt, greedy decoding and 40-packet window. S2 gets a 4,096-token allowance, top_p 0.95 and requested seed 17. The cases compare no dispatch, forced S2 with original dialogue context, forced S2 with user-only context, and S2 triggered by the model’s own control fields. The current audio selector includes those measured cases.')+labeled(4,['ID','Mode','Actual played transcript','391 heard'],[(c['id'],c['policy'],c['played_transcript'],c.get('correct_arithmetic_in_played_transcript',False)) for c in items],'Independent CPU transcription of actual model PCM; the full trace and returned speech fields are retained. User-only context is constructed from actual S1 ASR, not the reference answer.'))
    else:
        body+=section('The full arithmetic follow-up is queued',paragraphs('GPU job <b>1036593</b> repeats the verified S1 settings and 40-packet capture. It gives S2 a 4,096-token allowance, top_p 0.95 and requested seed 17, and compares the original dialogue context with S1’s actual user transcription alone. A fourth condition lets S1’s own THINK command trigger S2, without a forced control.', 'The same two-H100 isolation and latency calibration apply. CPU audit <b>1036609</b> depends on that GPU job and will collect played speech, guidance and allocation records afterwards. No arithmetic audio-handoff pass is claimed while these results are pending.'))
    body+=section('What changed in the harness',paragraphs('The original S1 loop and its published reproduction commands remain unchanged. The experiment adapter makes the GPU assignment explicit and corrects one training-protocol discrepancy in forced tests: when the model has not emitted THINK, it changes only that control value in the assistant history. The original model response is preserved and the intervention is logged. This keeps a forced S2 call from silently omitting the THINK cue that the training format expects.', 'The follow-up adds a declared user-only context option for this single-request setting. It obtains the question by joining the actual ASR fields returned by S1; it does not inject the expected number 391 or a reference assistant answer. The original dialogue context is kept as a control. Multi-turn assistance would need its full conversational context.')+'<p>Source: <a href="../research/s2-single/s2_single_adapter.py">Current experiment adapter</a> · <a href="../research/s2-single/initial_s2_adapter.py">Executed initial adapter</a> · <a href="../research/s2-single/probe_s2_single_provider.py">Provider diagnostic</a> · <a href="../research/s2-single/audit_s2_single.py">CPU speech audit</a>.</p>')
    body+=section('Evidence, scope and reproduction',paragraphs('The initial full study allocated two GPUs for 274 seconds, or <b>0.15222 GPU hours</b>. The provider diagnostic allocated one GPU for 54 seconds, or <b>0.015 GPU hours</b>. Startup, calibration and silent tails are included in those allocation costs. The follow-up is a separate sequential job; its actual cost is reported once complete.', 'This is a small controlled demonstration with a local Qwen3-4B Thinking substitute for the paper’s Gemini backend. It does not establish benchmark accuracy, arbitrary single-request reliability or physical microphone/loudspeaker latency. Original gaps remain in the replay. Only final guidance enters S1; private S2 text is not published.')+'<p><a href="../research/s2-single-study.json">Full reviewed records and lossless audio</a> · <a href="../research/s2-single/initial_config.json">Initial configuration</a> · <a href="../research/s2-single/followup_config.json">Follow-up configuration</a> · <a href="../research/natural-dailytalk/ATTRIBUTION.md">DailyTalk attribution and adaptation</a> · <a href="../research/flite/COPYING">Flite license</a> · <a href="s1-reproduction.html#inference-loop">Core inference-loop explanation</a>.</p><p>On the migrated cluster, the latest prepared experiment is launched from <code>~/cxiao/duplex</code> with:</p><pre><code>sbatch jobs/duplexomni_s2_single.sbatch .migration/updates/2026-10-09-s2-single/launch-02</code></pre><p>This requests two H100 SXM 80 GB GPUs and runs calibration before the cases. Check the existing job before submitting a duplicate. For a new completed job, run <code>envs/duplexomni/bin/python scripts/audit_s2_single.py --job NEW_JOB_ID</code>; the audit uses CPU only.</p>')
    body+='<footer class="site-footer"><p><a href="index.html">All experiments</a> · <a href="s1-reproduction.html">S1 reproduction report</a></p></footer>'
    selected={k:study[k] for k in ['conditions','audio','default_case']}
    script='''<script id="s2-study-data" type="application/json">'''+json.dumps(selected,ensure_ascii=False).replace('<','\\u003c')+'''</script><script>(()=>{const d=JSON.parse(document.getElementById('s2-study-data').textContent),s=document.getElementById('s2-case');for(const c of d.conditions){const o=document.createElement('option');o.value=c.id;o.textContent=c.id+' · '+c.label;s.append(o);}function show(){const c=d.conditions.find(c=>c.id===s.value),a=d.audio[c.id];for(const [id,value]of Object.entries({'condition-title':c.label,'condition-source':c.source+' · one request, no interruption · job '+c.job_id,'user-request':c.request,'condition-finding':c.finding,'played-transcript':c.played_transcript,'final-guidance':c.final_guidance.join(' ')||'No S2 call or complete guidance in this condition.','s2-detail':'Actual S2 requests: '+c.s2_request_count+'. Private reasoning characters: '+c.s2_reasoning_characters+'.'}))document.getElementById(id).textContent=value;for(const [id,uri]of [['s2-conversation',a.conversation],['s2-model',a.model]]){const e=document.getElementById(id);e.pause();e.src=uri;e.load();}}s.value=d.default_case;s.addEventListener('change',show);show();})();</script>'''
    style='<style>.study-table-scroll{overflow-x:auto;max-width:100%}.study-table-scroll table{min-width:720px}audio{width:100%;max-width:850px}pre{overflow-x:auto;padding:18px;background:var(--surface-2)}blockquote{margin:14px 0;padding:12px 18px;border-left:3px solid var(--accent)}.cap{font-size:14px;color:var(--muted)}select{max-width:100%;font:inherit}</style>'
    page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Audited one-request S2 reasoning, delivery and speech, with real replay and failed controls."><title>Single-request S2 study · AI2AI Duplex</title><link rel="stylesheet" href="../assets/site.css">'+style+'</head><body><header class="site-nav"><div class="nav-inner"><a class="brand" href="../index.html">AI2AI Duplex</a>'+project_tabs('experiments','../')+'</div></header><main><div class="container">'+body+'</div></main>'+script+'</body></html>'
    (ROOT/'experiments/s2-single.html').write_text(version_assets(page))
    collection=ROOT/'experiments/index.html';text=collection.read_text()
    card='<article class="card" id="s2-study-card"><span class="tag">S2 study</span><h3>Single-request reasoning</h3><p>A real Thinking-backend handoff, spoken results, arithmetic failure controls and the current follow-up.</p><p><a class="button" href="s2-single.html">Read the S2 study</a></p></article>'
    if 'id="s2-study-card"' not in text:text=text.replace('<div class="card-grid">','<div class="card-grid">'+card,1)
    text=text.replace('Current focus · 8 October 2026','Current studies · 9 October 2026')
    text=text.replace('<h1>One human request. One interruption.</h1>','<h1>Speech, interruption and reasoning.</h1>')
    text=text.replace('Original DailyTalk human recordings, a matched S1-only control, and actual model playback. Earlier diagnostic results are separated.',
        'Verified S1 speech and interruption examples, followed by single-request S2 experiments. Each study links its actual audio, controls and limitations.')
    collection.write_text(text)
    print('Built single-request S2 study and collection link.')


if __name__=='__main__':main()
