"""Render the current human-recorded request/interruption and its audited results."""
from html import escape
import json

from build_current_experiments import ROOT,hk,project_tabs,table,version_assets

def main():
    bundle=json.loads((ROOT/'research/current-natural.json').read_text())
    review=json.loads((ROOT/'research/natural-interruption-review.json').read_text())
    interrupted=next(c for c in review['cases'] if c['id']=='N2b');metric=interrupted['interruption']
    initial=review['source_manifest']['clips'][0]['text'];clarification=review['source_manifest']['clips'][1]['text']
    intro='<section class="section"><h2>One human request, one clarification</h2><p><b>Initial request</b></p><blockquote id="current-request" class="example-answer">'+escape(initial)+'</blockquote><p><b>Clarification during model speech</b></p><blockquote id="current-clarification" class="example-answer">'+escape(clarification)+'</blockquote><p>These are original human recordings from DailyTalk conversation 656, the same speaker’s turns 2 and 4. DailyTalk contains scripted human dialogues. We crop only this user’s audio and schedule the clarification during actual S1 playback; the original counterpart’s answer is never model input. This is an adapted barge-in control, not an untouched naturally occurring interruption.</p><div class="callout"><strong>Native stop and spoken clarification demonstrated · job '+review['job_id']+'</strong><p>The model’s first explanation is interrupted mid-sentence. S1 emits [STOP], drops 0.28 s of queued old audio, and answers the clarification. Actual human/model overlap is 0.40 s; stopping is about 0.49 s after measured nonquiet user onset. Both conditions use one H100 80 GB, all S1 components on GPU 0, and no S2. <a href="natural-study.html">Read the evidence and limitations</a>.</p></div></section>'
    values={'TITLE':'Human interruption · S1 only','DESCRIPTION':'A real human asks one question and interrupts once with a clarification.',
        'NAV':project_tabs('experiments','../'),'EXAMPLE_INTRO':intro,
        'EXAMPLE':json.dumps(bundle,ensure_ascii=False).replace('<','\\u003c'),'DATA_URL':'../research/current-natural.json',
        'OTHER_EXPERIMENT':'<a href="single-request.html">Basic S1 checks</a>'}
    page=(ROOT/'scripts/templates/current_trajectory.html.in').read_text()
    for k,v in values.items():page=page.replace('{{'+k+'}}',v)
    page=page.replace('Current controlled study · 8 October 2026','Human-recorded dialogue · 8 October 2026')
    page=page.replace('<a href="controlled-study.html">Study status and criteria</a>','<a href="natural-study.html">Interruption evidence</a>')
    page=page.replace('Input previews contain authored synthetic speech. Completed replays contain actual model playback;','Human user recording and actual model playback;')
    page=page.replace('Input, S1, S2 and Talker events when the run has completed.','Captured human input, S1 requests, native STOP and actual playback; S2 is absent.')
    old='<p class="meta">Authored prompts, synthesized on CPU with the Flite SLT voice. <a href="../research/flite/COPYING">Flite attribution and license</a> · <a href="../research/current-study.json">Source and run record</a>.</p>'
    new='<p class="meta">Human user audio: <a href="https://github.com/keonlee9420/DailyTalk">DailyTalk</a>, stereo packaging by <a href="https://huggingface.co/datasets/kyutai/DailyTalkContiguous">Kyutai</a>. Cropped/resampled human audio and combined replay: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>. <a href="../research/natural-dailytalk/manifest.json">Exact source and sample bounds</a> · <a href="../research/natural-dailytalk/ATTRIBUTION.md">Attribution and changes</a>.</p>'
    assert old in page;page=page.replace(old,new);assert '{{' not in page
    for name in ['trajectory.html','interruption.html']:(ROOT/'experiments'/name).write_text(version_assets(page))

    body='<header class="site-nav"><div class="nav-inner"><a class="brand" href="../index.html">AI2AI Duplex</a>'+project_tabs('experiments','../')+'</div></header>'
    body+=hk.hero('Natural speech test · 8 October 2026','S1 yields and answers the clarification.','One human-recorded question, one same-speaker clarification during model speech, and S2 entirely absent.')
    body+=hk.section('Observed interaction',body='<p>The human asks about outlet stores. S1 starts its explanation. During that speech, the human asks <b>“Faulty products?”</b>. The model emits a native <code>[STOP]</code>, invalidates old queued audio, and gives a new spoken answer. Independent transcription captures the audible cut: <b>“An outlet is a… No, not faulty products. Outlets sell genuine items at discounted prices.”</b></p><p>This demonstrates stopping and clarification uptake in this example. The categorical “not faulty” answer is simplistic; interaction success does not establish comprehensive factual accuracy or general interruption robustness.</p><p><a class="button" href="interruption.html">Listen to actual human/model replay</a> · <a href="index.html">All experiments</a>.</p>')
    rows=[('N2a','Same human question, no interruption','Complete outlet explanation',0),('N2b','Same question + Faulty products?','Native STOP and new clarification reply',1)]
    body+=hk.section('Matched conditions',body=hk.labeled_asset(table(['ID','Human input','Observed behavior','Native STOP count'],rows),'Table',1,'Greedy decoding, native patience/short-clear prompt, raw assistant history. Returned fields are identical for the first 12 ticks before the interruption. All source counterpart audio is excluded.'))
    rows=[('Human/model nonquiet overlap','0.40 s'),('STOP delay from first correction packet',f"{metric['stop_delay_from_packet_seconds']:.3f} s"),('STOP delay from nonquiet user onset',f"{metric['stop_delay_from_nonquiet_user_onset_seconds']:.3f} s"),('Queued obsolete audio removed','13,440 bytes = 0.28 s PCM'),('Old-epoch nonquiet packets after STOP','0'),('Correction packets processed','3 / 3'),('S2 requests','0'),('p95 S1 · interrupted case',f"{interrupted['p95_s1_seconds']:.3f} s"),('p95 Talker · calibration',f"{review['runtime_qualification']['baseline']['p95_talker_seconds']:.3f} s")]
    body+=hk.section('Timing and playback evidence',body=hk.labeled_asset(table(['Measurement','Value'],rows),'Table',2,'Measured software queues and PCM on a 20 ms analysis grid. Packet onset and actual nonquiet user onset differ; neither is precise acoustic word alignment. Request budget is 480 ms.'))
    examples=''
    for c in review['cases']:
        examples+='<article class="card"><h3>'+c['id']+'</h3><p><b>S1 ASR:</b> '+escape(c['generated_asr'])+'</p><p><b>Actual spoken transcript:</b> '+escape(c['played_transcript'])+'</p></article>'
    body+=hk.section('Inspect the content',body='<div class="card-grid">'+examples+'</div><p>The interrupted model text includes “a store” before STOP, but the audible replay cuts that queued continuation. Actual PCM and source epoch tags, rather than synthesized-but-discarded clips, determine the stopping result.</p>')
    body+=hk.section('Source and adaptation',body='<p><a href="https://github.com/keonlee9420/DailyTalk">DailyTalk</a> is a human-recorded conversational TTS dataset based on scripted DailyDialog dialogues. These inputs are recorded people, not TTS-generated user speech. We use <a href="https://huggingface.co/datasets/kyutai/DailyTalkContiguous">Kyutai’s pinned stereo release</a>, conversation 656, speaker/channel 1, original turns 2 and 4. The request and clarification are cropped, resampled from 44.1 kHz to 24 kHz, and scheduled relative to actual model playback. No speed, volume, or voice conversion is applied to the user crops.</p><p>Independent input transcription recovers all semantic words; it omits the filler “Umm” and question punctuation. The original waveform is retained. <a href="../research/natural-dailytalk/manifest.json">Exact checksums and source sample bounds</a> · <a href="../research/natural-dailytalk/ATTRIBUTION.md">CC BY-SA 4.0 attribution and adaptation</a>.</p>')
    attempts=[(r['job'],r['gpu_type'],r['result'],f"{r['gpu_hours']:.5f}") for r in review['attempts']]
    body+=hk.section('What the preliminary controls found',body='<p>The first dinner proposal was correctly transcribed but silent. Its later latency spikes coincide with dropping the cached history prefix after tick 40; the earlier question itself had p95 0.316 s and negligible backlog. That no-answer behavior is therefore separate from the late cache issue. The new test uses a predefined 40-tick window and a factual request, while the longer-stream cache problem remains open.</p><p>Temperature 0.8, used by the authors’ realtime harness, produced a native STOP in a preliminary interruption case, but also an unwanted greeting and requests for disabled S2. Greedy decoding produces the complete human-question answer and the demonstrated clarification response. The final matched pair changes only the actual user clarification after an identical generated prefix.</p>'+hk.labeled_asset(table(['Job','GPU / 80 GB each','Observed result','GPU hours'],attempts),'Table',3,'Actual allocations are sequential, maximum one GPU active. The unallocated overnight two-H100 request was cancelled. These controls are diagnostic observations, not benchmark success rates.'))
    body+=hk.section('Runtime and limitations',body='<p>Final job 1035079 completed on one H100 SXM 80 GB. Thinker, Talker, MTP and Code2Wav share GPU 0; S2 is not loaded. Runtime qualification passed before the interruption. Allocation was 130 s (0.03611 GPU hours); all three actual GPU allocations total 0.13556 GPU hours. No experiment GPU remains active.</p><ul>'+''.join('<li>'+escape(s)+'</li>' for s in review['limitations'])+'</ul><p><a href="../research/natural-interruption-review.json">Full evidence review</a> · <a href="../research/current-natural.json">Both audio traces</a> · <a href="single-request.html">Earlier basic S1 checks</a> · <a href="archive.html">Earlier studies</a>.</p>')
    full,_=hk.document('Human interruption · S1-only evidence',body,head_html='<link rel="stylesheet" href="../assets/site.css"><style>.study-table-scroll{overflow-x:auto;max-width:100%}.study-table-scroll table{min-width:650px}</style>')
    (ROOT/'experiments/natural-study.html').write_text(full)
    cards=[('Current','Human interruption','One human question and one clarification during S1 speech. Compare uninterrupted and interrupted playback.','interruption.html','Listen to the pair'),('Evidence','Stop, reply and limitations','Native STOP, exact queued-audio cut, independent transcripts, timing and sampling controls.','natural-study.html','Read the evidence'),('Basic checks','Single-request S1','Earlier factual/repeat controls establish basic speech; the new default uses human recordings.','single-request.html','View basic checks'),('Archive','Earlier diagnostics','Earlier S2, synthetic interruption, budget and decoder experiments retain their failure verdicts.','archive.html','Browse archive')]
    content=''.join('<article class="card"><span class="tag">'+tag+'</span><h3>'+title+'</h3><p>'+desc+'</p><p><a class="button" href="'+url+'">'+button+'</a></p></article>' for tag,title,desc,url,button in cards)
    page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Human-recorded S1 interruption, matched control and evidence."><title>Experiments · AI2AI Duplex</title><link rel="stylesheet" href="../assets/site.css"></head><body><header class="site-nav"><div class="nav-inner"><a class="brand" href="../index.html">AI2AI Duplex</a>'+project_tabs('experiments','../')+'</div></header><main><div class="container"><header class="hero"><p class="eyebrow">Current focus · 8 October 2026</p><h1>One human request. One interruption.</h1><p class="lede">Original DailyTalk human recordings, a matched S1-only control, and actual model playback. Earlier diagnostic results are separated.</p></header><section class="section"><h2>Current experiment and evidence</h2><div class="card-grid">'+content+'</div></section></div></main></body></html>'
    (ROOT/'experiments/index.html').write_text(version_assets(page))
    print('Built current natural interruption, evidence and collection.')

if __name__=='__main__':main()
