"""Evidence-led summary for the measured interaction grid."""
from html import escape
import json


def build(root):
    rows=json.loads((root/'research/interactive-review.json').read_text())['rows']
    table=[]
    for r in rows:
        terms=r['question_terms_in_asr']
        values=[r['job_id'],r['name'],f"{r['gpus']} × {r['hardware']}; Thinker TP{r['thinker_tp']}",
            f"{r['input_seconds']:.2f}",f"{r['input_packet_rtf']:.3f}",f"{r['mean_s1_seconds']:.3f}",
            f"{r['codec_duration_loss_seconds']:.6f}",
            '/'.join('yes' if terms[k] else 'no' for k in ['working_on','budget','money'])]
        table.append('<tr>'+''.join('<td>'+escape(str(v))+'</td>' for v in values)+'</tr>')
    best=min(r['input_packet_rtf'] for r in rows)
    return f'''<section class="section" aria-labelledby="example-title"><h2 id="example-title">Interaction reproduction · timing and answer quality</h2><p class="section-intro">Paced input, question recognition, speech decoding and response correctness are separate checks. Select a measured case below and listen to the clocked user-left/Talker-right replay. Waiting and listening silence is retained.</p><div class="example-cards"><article class="card"><span class="tag blue">Input</span><h3>The old clip cuts the third question</h3><p>The original audition sends the 10-second recording as one request, then sends silence. Independent transcription ends at “How much money can”. The complete channel contains “How much money can you spend?” and further turns. New runs feed real 480 ms packets.</p></article><article class="card"><span class="tag amber">Speech</span><h3>Repeated decoder warmup is corrected</h3><p>The stock decoder restarts on every six-frame call. Across 100 chunks it loses 2.3125 seconds. Bounded 25-frame context returns the full 480 ms increment after the first call; total startup loss is 0.023125 seconds. This fixes duration, not all listening or waiting silence.</p></article><article class="card"><span class="tag amber">Quality</span><h3>Recognition does not prove a valid answer</h3><p>The generic English prompt recovers working/budget/money in ASR. Earlier outputs discuss unrelated colors; later outputs claim a budget database or finance team that does not exist. The grid retains answer-quality failures instead of declaring transport a successful conversation.</p></article></div><div class="table-wrap"><table><caption>Table 1. Measured interaction grid. Packet RTF is case wall time divided by processed input packets, including silent tail and playback drain; real-time processing needs RTF at most 1. Mean S1 is client request time. Question columns are lexical recognition checks, not response correctness.</caption><thead><tr><th>Job</th><th>Case</th><th>Allocation</th><th>User input (s)</th><th>Packet RTF</th><th>Mean S1 (s)</th><th>Decoder loss (s)</th><th>Working / budget / money in ASR</th></tr></thead><tbody>{''.join(table)}</tbody></table></div><p class="meta">Best measured packet RTF in this grid: {best:.3f}. Source artifacts: per-case native summaries, saved RVQ codes and independent CPU Whisper transcripts. The <a href="../research/interactive-review.json">machine-readable audit</a> and <a href="interaction-review.html">standard evidence review</a> keeps generated ASR, tts, audio gaps and exact case identifiers.</p><div class="callout amber"><strong>Software playback, measured clock</strong><p>The default stereo clip contains packets emitted by the test playback buffer with their observed timestamps. It is not a physical microphone/speaker recording. The alternative concatenated clip removes wall-clock waiting, retains listening chunks, and cannot establish live response speed.</p></div></section>'''
